# @generated by spec/generator — DO NOT EDIT.
# Source: https://ag-ui.com/spec/1.0/schema.json
# Regenerate: pnpm --filter @ag-ui/spec generate

"""
The generated protocol models: the internal source ag_ui.core re-exports.
Regenerate with `pnpm --filter @ag-ui/spec generate`; the shape follows the
schema.
"""
