packages:
  - apps/*
  - spec
  - middlewares/*
  - sdks/typescript/packages/*
  - sdks/dotnet/tests/CrossLanguage.Vitest
  - integrations/*/typescript
  - integrations/community/*/typescript
  - integrations/aws-strands/typescript/examples
  - integrations/mastra/typescript/examples

ignoredBuiltDependencies:
  - nx
