import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Recaptured using pinned CopilotKit 1.70.1, whose interrupt resume intentionally continues the original logical run ID; previous captures used stale installed 1.61.2.
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '"Meeting scheduled for Sat, Sep 12, 10:00 AM: Intro call to discuss pricing"' as const;
const shared2 = [
  {
    type: "RUN_STARTED",
    threadId: "id-1",
    runId: "id-2",
    input: {
      threadId: "id-1",
      runId: "id-2",
      state: {},
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
      ],
      tools: [],
      context: [],
      forwardedProps: {},
    },
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Book an intro call with the sales team to discuss pricing.",
      },
    ],
  },
  {
    type: "TOOL_CALL_START",
    toolCallId: "id-4",
    toolCallName: "schedule_meeting",
    parentMessageId: "id-5",
  },
  {
    type: "TOOL_CALL_ARGS",
    toolCallId: "id-4",
    delta: '{"topic":"Intro call',
  },
  {
    type: "TOOL_CALL_ARGS",
    toolCallId: "id-4",
    delta: ' to discuss pricing"',
  },
  {
    type: "TOOL_CALL_ARGS",
    toolCallId: "id-4",
    delta: ',"attendee":"the sal',
  },
  {
    type: "TOOL_CALL_ARGS",
    toolCallId: "id-4",
    delta: 'es team"}',
  },
  {
    type: "TOOL_CALL_END",
    toolCallId: "id-4",
  },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Book an intro call with the sales team to discuss pricing.",
      },
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "schedule_meeting",
              arguments:
                '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
            },
          },
        ],
      },
    ],
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "RUN_FINISHED",
    threadId: "id-1",
    runId: "id-2",
    outcome: {
      type: "interrupt",
      interrupts: [
        {
          id: "v1:tool_call:call_schedule_meeting_1:340a4daa-b874-5aad-8309-a63b92d507dd",
          reason: "schedule_meeting",
          metadata: {
            reason: {
              topic: "Intro call to discuss pricing",
              attendee: "the sales team",
            },
          },
        },
      ],
    },
    usage: [
      {
        provider: "openai",
        model: "gpt-5.4",
        inputTokens: 176,
        outputTokens: 22,
        totalTokens: 198,
      },
    ],
  },
  {
    type: "RUN_STARTED",
    threadId: "id-1",
    runId: "id-2",
    input: {
      threadId: "id-1",
      runId: "id-2",
      state: {},
      messages: [
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: {
                name: "schedule_meeting",
                arguments:
                  '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
              },
            },
          ],
        },
      ],
      tools: [],
      context: [],
      forwardedProps: {},
      resume: [
        {
          interruptId:
            "v1:tool_call:call_schedule_meeting_1:340a4daa-b874-5aad-8309-a63b92d507dd",
          status: "resolved",
          payload: {
            cancelled: true,
          },
        },
      ],
    },
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Book an intro call with the sales team to discuss pricing.",
      },
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "schedule_meeting",
              arguments:
                '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
            },
          },
        ],
      },
    ],
  },
  {
    type: "TOOL_CALL_RESULT",
    messageId: "id-6",
    toolCallId: "id-4",
    content:
      '"User cancelled. Meeting NOT scheduled: Intro call to discuss pricing"',
  },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Book an intro call with the sales team to discuss pricing.",
      },
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "schedule_meeting",
              arguments:
                '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
            },
          },
        ],
      },
      {
        id: "id-6",
        content:
          '"User cancelled. Meeting NOT scheduled: Intro call to discuss pricing"',
        role: "tool",
        toolCallId: "id-4",
      },
    ],
  },
  {
    type: "TEXT_MESSAGE_START",
    messageId: "id-7",
    role: "assistant",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-7",
    delta: "No problem, I did no",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-7",
    delta: "t schedule anything.",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-7",
    delta: " Tell me what you wo",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-7",
    delta: "uld like instead.",
  },
  {
    type: "TEXT_MESSAGE_END",
    messageId: "id-7",
  },
  {
    type: "MESSAGES_SNAPSHOT",
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Book an intro call with the sales team to discuss pricing.",
      },
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "schedule_meeting",
              arguments:
                '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
            },
          },
        ],
      },
      {
        id: "id-6",
        content:
          '"User cancelled. Meeting NOT scheduled: Intro call to discuss pricing"',
        role: "tool",
        toolCallId: "id-4",
      },
      {
        id: "id-7",
        role: "assistant",
        content:
          "No problem, I did not schedule anything. Tell me what you would like instead.",
      },
    ],
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "RUN_FINISHED",
    threadId: "id-1",
    runId: "id-2",
    outcome: {
      type: "success",
    },
    usage: [
      {
        provider: "openai",
        model: "gpt-5.4",
        inputTokens: 193,
        outputTokens: 20,
        totalTokens: 213,
      },
    ],
  },
] as const;
const shared3 = {
  id: "id-6",
  content: shared1,
  role: "tool",
  toolCallId: "id-4",
} as const;

export const interruptPageEventTrace = defineEventTrace(import.meta.url, {
  cancellingLeavesNothingScheduled: shared2,
  pausesTheToolAndOffersTheUserATime: shared2,
  resumingCarriesTheChosenTimeIntoTheTool: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content:
              "Book an intro call with the sales team to discuss pricing.",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
      ],
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-4",
      toolCallName: "schedule_meeting",
      parentMessageId: "id-5",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"topic":"Intro call',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ' to discuss pricing"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"attendee":"the sal',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'es team"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: {
                name: "schedule_meeting",
                arguments:
                  '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
              },
            },
          ],
        },
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      outcome: {
        type: "interrupt",
        interrupts: [
          {
            id: "v1:tool_call:call_schedule_meeting_1:340a4daa-b874-5aad-8309-a63b92d507dd",
            reason: "schedule_meeting",
            metadata: {
              reason: {
                topic: "Intro call to discuss pricing",
                attendee: "the sales team",
              },
            },
          },
        ],
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 176,
          outputTokens: 22,
          totalTokens: 198,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {},
        messages: [
          {
            id: "id-5",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-4",
                type: "function",
                function: {
                  name: "schedule_meeting",
                  arguments:
                    '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
                },
              },
            ],
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
        resume: [
          {
            interruptId:
              "v1:tool_call:call_schedule_meeting_1:340a4daa-b874-5aad-8309-a63b92d507dd",
            status: "resolved",
            payload: {
              chosen_time: "2026-09-12T10:00:00.000Z",
              chosen_label: "Sat, Sep 12, 10:00 AM",
            },
          },
        ],
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: {
                name: "schedule_meeting",
                arguments:
                  '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
              },
            },
          ],
        },
      ],
    },
    {
      type: "TOOL_CALL_RESULT",
      messageId: "id-6",
      toolCallId: "id-4",
      content: shared1,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: {
                name: "schedule_meeting",
                arguments:
                  '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
              },
            },
          ],
        },
        shared3,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-7",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: "Your meeting is sche",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: "duled for Sat, Sep 1",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: "2, 10:00 AM. Looking",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: " forward to it!",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-7",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Book an intro call with the sales team to discuss pricing.",
        },
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: {
                name: "schedule_meeting",
                arguments:
                  '{"topic":"Intro call to discuss pricing","attendee":"the sales team"}',
              },
            },
          ],
        },
        shared3,
        {
          id: "id-7",
          role: "assistant",
          content:
            "Your meeting is scheduled for Sat, Sep 12, 10:00 AM. Looking forward to it!",
        },
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      outcome: {
        type: "success",
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 194,
          outputTokens: 19,
          totalTokens: 213,
        },
      ],
    },
  ],
});
