import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Collapse exact LangGraph messages/events mirrors even when load interleaves unrelated events
// Before accepting changes, verify whether the implementation regressed.
const shared1 = {
  output: {
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 8,
            completion_tokens: 9,
            total_tokens: 17,
          },
        },
        tool_call_chunks: [],
        tool_calls: [],
        id: "id-15",
        usage_metadata: {
          input_tokens: 8,
          output_tokens: 9,
          total_tokens: 17,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        name: "model",
        type: "ai",
      },
    ],
    copilotkit: {
      actions: [],
    },
  },
  input: {
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 8,
            completion_tokens: 9,
            total_tokens: 17,
          },
        },
        tool_call_chunks: [],
        tool_calls: [],
        id: "id-15",
        usage_metadata: {
          input_tokens: 8,
          output_tokens: 9,
          total_tokens: 17,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        name: "model",
        type: "ai",
      },
    ],
    copilotkit: {
      actions: [],
    },
  },
} as const;
const shared2 = {
  event: "on_chat_model_stream",
  data: {
    chunk: {
      content: "Hello! How can I ass",
      tool_call_chunks: [],
      additional_kwargs: {},
      id: "id-15",
      response_metadata: {
        model_provider: "openai",
        usage: {},
      },
      tool_calls: [],
      invalid_tool_calls: [],
      type: "ai",
    },
  },
  run_id: "id-13",
  name: "ChatOpenAI",
  tags: [],
  metadata: {
    ls_integration: "langchain_chat_model",
    created_by: "system",
    graph_id: "agentic_chat",
    assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
    run_attempt: 1,
    langgraph_version: "<langgraph-version>",
    langgraph_plan: "developer",
    langgraph_host: "self-hosted",
    langgraph_api_url: "<langgraph-api-url>",
    thread_id: "id-1",
    run_id: "id-6",
    langgraph_step: 2,
    langgraph_node: "model_request",
    langgraph_triggers: ["branch:to:model_request"],
    langgraph_path: ["__pregel_pull", "model_request"],
    langgraph_checkpoint_ns: "model_request:id-11",
    checkpoint_ns: "model_request:id-11",
    ls_provider: "openai",
    ls_model_name: "gpt-4o",
    ls_model_type: "chat",
    versions: {
      "@langchain/core": "1.1.46",
    },
  },
} as const;
const shared3 = {
  event: "on_chat_model_stream",
  data: {
    chunk: {
      content: "",
      tool_call_chunks: [],
      additional_kwargs: {},
      id: "id-15",
      response_metadata: {
        model_provider: "openai",
        usage: {},
      },
      tool_calls: [],
      invalid_tool_calls: [],
      type: "ai",
    },
  },
  run_id: "id-13",
  name: "ChatOpenAI",
  tags: [],
  metadata: {
    ls_integration: "langchain_chat_model",
    created_by: "system",
    graph_id: "agentic_chat",
    assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
    run_attempt: 1,
    langgraph_version: "<langgraph-version>",
    langgraph_plan: "developer",
    langgraph_host: "self-hosted",
    langgraph_api_url: "<langgraph-api-url>",
    thread_id: "id-1",
    run_id: "id-6",
    langgraph_step: 2,
    langgraph_node: "model_request",
    langgraph_triggers: ["branch:to:model_request"],
    langgraph_path: ["__pregel_pull", "model_request"],
    langgraph_checkpoint_ns: "model_request:id-11",
    checkpoint_ns: "model_request:id-11",
    ls_provider: "openai",
    ls_model_name: "gpt-4o",
    ls_model_type: "chat",
    versions: {
      "@langchain/core": "1.1.46",
    },
  },
} as const;
const shared4 = {
  ls_integration: "langgraph",
  created_by: "system",
  graph_id: "agentic_chat",
  assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
  run_attempt: 1,
  langgraph_version: "<langgraph-version>",
  langgraph_plan: "developer",
  langgraph_host: "self-hosted",
  langgraph_api_url: "<langgraph-api-url>",
  thread_id: "id-1",
  run_id: "id-6",
  langgraph_step: 1,
  langgraph_node: "CopilotKitMiddleware.before_agent",
  langgraph_triggers: ["branch:to:CopilotKitMiddleware.before_agent"],
  langgraph_path: ["__pregel_pull", "CopilotKitMiddleware.before_agent"],
  langgraph_checkpoint_ns: "CopilotKitMiddleware.before_agent:id-7",
  checkpoint_ns: "CopilotKitMiddleware.before_agent:id-7",
} as const;
const shared5 = {
  ls_integration: "langgraph",
  created_by: "system",
  graph_id: "agentic_chat",
  assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
  run_attempt: 1,
  langgraph_version: "<langgraph-version>",
  langgraph_plan: "developer",
  langgraph_host: "self-hosted",
  langgraph_api_url: "<langgraph-api-url>",
  thread_id: "id-1",
  run_id: "id-6",
  langgraph_step: 3,
  langgraph_node: "CopilotKitMiddleware.after_model",
  langgraph_triggers: ["branch:to:CopilotKitMiddleware.after_model"],
  langgraph_path: ["__pregel_pull", "CopilotKitMiddleware.after_model"],
  langgraph_checkpoint_ns: "CopilotKitMiddleware.after_model:id-21",
  checkpoint_ns: "CopilotKitMiddleware.after_model:id-21",
} as const;
const shared6 = {
  ls_integration: "langgraph",
  created_by: "system",
  graph_id: "agentic_chat",
  assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
  run_attempt: 1,
  langgraph_version: "<langgraph-version>",
  langgraph_plan: "developer",
  langgraph_host: "self-hosted",
  langgraph_api_url: "<langgraph-api-url>",
  thread_id: "id-1",
  run_id: "id-6",
  langgraph_step: 4,
  langgraph_node: "CopilotKitMiddleware.after_agent",
  langgraph_triggers: ["branch:to:CopilotKitMiddleware.after_agent"],
  langgraph_path: ["__pregel_pull", "CopilotKitMiddleware.after_agent"],
  langgraph_checkpoint_ns: "CopilotKitMiddleware.after_agent:id-28",
  checkpoint_ns: "CopilotKitMiddleware.after_agent:id-28",
} as const;
const shared7 = {
  ls_integration: "langgraph",
  created_by: "system",
  graph_id: "agentic_chat",
  assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
  run_attempt: 1,
  langgraph_version: "<langgraph-version>",
  langgraph_plan: "developer",
  langgraph_host: "self-hosted",
  langgraph_api_url: "<langgraph-api-url>",
  thread_id: "id-1",
  run_id: "id-6",
  langgraph_step: 2,
  langgraph_node: "model_request",
  langgraph_triggers: ["branch:to:model_request"],
  langgraph_path: ["__pregel_pull", "model_request"],
  langgraph_checkpoint_ns: "model_request:id-11",
  checkpoint_ns: "model_request:id-11",
} as const;
const shared8 = {
  input: {
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 8,
            completion_tokens: 9,
            total_tokens: 17,
          },
        },
        tool_call_chunks: [],
        tool_calls: [],
        id: "id-15",
        usage_metadata: {
          input_tokens: 8,
          output_tokens: 9,
          total_tokens: 17,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        name: "model",
        type: "ai",
      },
    ],
    copilotkit: {
      actions: [],
    },
  },
} as const;
const shared9 = {
  messages: [
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 8,
          completion_tokens: 9,
          total_tokens: 17,
        },
      },
      tool_call_chunks: [],
      tool_calls: [],
      id: "id-15",
      usage_metadata: {
        input_tokens: 8,
        output_tokens: 9,
        total_tokens: 17,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      name: "model",
      type: "ai",
    },
  ],
  copilotkit: {
    actions: [],
  },
} as const;
const shared10 = {
  messages: [
    [
      {
        content: [
          {
            type: "text",
            text: "You are a helpful assistant.",
          },
        ],
        additional_kwargs: {},
        response_metadata: {},
        type: "system",
      },
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
    ],
  ],
} as const;
const shared11 = {
  input: {
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
    ],
    copilotkit: {
      actions: [],
    },
  },
} as const;

export const v1AgenticChatPageEventTrace = defineEventTrace(import.meta.url, {
  langgraphTypeScriptSendsAndReceivesAMessage: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Hi",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-4",
        event: "events",
        data: {
          event: "on_chain_start",
          data: shared11,
          name: "CopilotKitMiddleware.before_agent",
          tags: ["graph:step:1"],
          run_id: "id-5",
          metadata: shared4,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-8",
        event: "events",
        data: {
          event: "on_chain_end",
          data: {
            output: {
              messages: [
                {
                  id: "id-3",
                  content: "Hi",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                },
              ],
              copilotkit: {
                actions: [],
              },
            },
            input: {
              messages: [
                {
                  id: "id-3",
                  content: "Hi",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                },
              ],
              copilotkit: {
                actions: [],
              },
            },
          },
          run_id: "id-5",
          name: "CopilotKitMiddleware.before_agent",
          tags: ["graph:step:1"],
          metadata: shared4,
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model_request",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-9",
        event: "events",
        data: {
          event: "on_chain_start",
          data: shared11,
          name: "model_request",
          tags: ["graph:step:2"],
          run_id: "id-10",
          metadata: shared7,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-12",
        event: "events",
        data: {
          event: "on_chat_model_start",
          data: {
            input: shared10,
          },
          name: "ChatOpenAI",
          tags: [],
          run_id: "id-13",
          metadata: {
            ls_integration: "langchain_chat_model",
            created_by: "system",
            graph_id: "agentic_chat",
            assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
            run_attempt: 1,
            langgraph_version: "<langgraph-version>",
            langgraph_plan: "developer",
            langgraph_host: "self-hosted",
            langgraph_api_url: "<langgraph-api-url>",
            thread_id: "id-1",
            run_id: "id-6",
            langgraph_step: 2,
            langgraph_node: "model_request",
            langgraph_triggers: ["branch:to:model_request"],
            langgraph_path: ["__pregel_pull", "model_request"],
            langgraph_checkpoint_ns: "model_request:id-11",
            checkpoint_ns: "model_request:id-11",
            ls_provider: "openai",
            ls_model_name: "gpt-4o",
            ls_model_type: "chat",
            versions: {
              "@langchain/core": "1.1.46",
            },
          },
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-14",
        event: "events",
        data: shared3,
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-16",
        event: "events",
        data: shared2,
      },
    },
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-15",
      rawEvent: shared2,
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-15",
      delta: "Hello! How can I ass",
      rawEvent: shared2,
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-15",
      delta: "ist you today?",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "ist you today?",
            tool_call_chunks: [],
            additional_kwargs: {},
            id: "id-15",
            response_metadata: {
              model_provider: "openai",
              usage: {},
            },
            tool_calls: [],
            invalid_tool_calls: [],
            type: "ai",
          },
        },
        run_id: "id-13",
        name: "ChatOpenAI",
        tags: [],
        metadata: {
          ls_integration: "langchain_chat_model",
          created_by: "system",
          graph_id: "agentic_chat",
          assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
          run_attempt: 1,
          langgraph_version: "<langgraph-version>",
          langgraph_plan: "developer",
          langgraph_host: "self-hosted",
          langgraph_api_url: "<langgraph-api-url>",
          thread_id: "id-1",
          run_id: "id-6",
          langgraph_step: 2,
          langgraph_node: "model_request",
          langgraph_triggers: ["branch:to:model_request"],
          langgraph_path: ["__pregel_pull", "model_request"],
          langgraph_checkpoint_ns: "model_request:id-11",
          checkpoint_ns: "model_request:id-11",
          ls_provider: "openai",
          ls_model_name: "gpt-4o",
          ls_model_type: "chat",
          versions: {
            "@langchain/core": "1.1.46",
          },
        },
      },
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-15",
      rawEvent: shared3,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-17",
        event: "events",
        data: {
          event: "on_chat_model_end",
          data: {
            output: {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 8,
                  completion_tokens: 9,
                  total_tokens: 17,
                },
              },
              tool_call_chunks: [],
              tool_calls: [],
              id: "id-15",
              usage_metadata: {
                input_tokens: 8,
                output_tokens: 9,
                total_tokens: 17,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
            input: shared10,
          },
          run_id: "id-13",
          name: "ChatOpenAI",
          tags: [],
          metadata: {
            ls_integration: "langchain_chat_model",
            created_by: "system",
            graph_id: "agentic_chat",
            assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
            run_attempt: 1,
            langgraph_version: "<langgraph-version>",
            langgraph_plan: "developer",
            langgraph_host: "self-hosted",
            langgraph_api_url: "<langgraph-api-url>",
            thread_id: "id-1",
            run_id: "id-6",
            langgraph_step: 2,
            langgraph_node: "model_request",
            langgraph_triggers: ["branch:to:model_request"],
            langgraph_path: ["__pregel_pull", "model_request"],
            langgraph_checkpoint_ns: "model_request:id-11",
            checkpoint_ns: "model_request:id-11",
            ls_provider: "openai",
            ls_model_name: "gpt-4o",
            ls_model_type: "chat",
            versions: {
              "@langchain/core": "1.1.46",
            },
          },
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared9,
      rawEvent: {
        id: "id-18",
        event: "events",
        data: {
          event: "on_chain_end",
          data: {
            output: {
              messages: [
                {
                  content: "Hello! How can I assist you today?",
                  additional_kwargs: {},
                  response_metadata: {
                    model_provider: "openai",
                    usage: {
                      prompt_tokens: 8,
                      completion_tokens: 9,
                      total_tokens: 17,
                    },
                  },
                  tool_call_chunks: [],
                  tool_calls: [],
                  id: "id-15",
                  usage_metadata: {
                    input_tokens: 8,
                    output_tokens: 9,
                    total_tokens: 17,
                    input_token_details: {},
                    output_token_details: {},
                  },
                  invalid_tool_calls: [],
                  name: "model",
                  type: "ai",
                },
              ],
            },
            input: {
              messages: [
                {
                  id: "id-3",
                  content: "Hi",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                },
              ],
              copilotkit: {
                actions: [],
              },
            },
          },
          run_id: "id-10",
          name: "model_request",
          tags: ["graph:step:2"],
          metadata: shared7,
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "model_request",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared9,
      rawEvent: {
        id: "id-19",
        event: "events",
        data: {
          event: "on_chain_start",
          data: shared8,
          name: "CopilotKitMiddleware.after_model",
          tags: ["graph:step:3"],
          run_id: "id-20",
          metadata: shared5,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-22",
        event: "events",
        data: {
          event: "on_chain_start",
          data: shared8,
          name: "RunnableLambda",
          tags: [],
          run_id: "id-23",
          metadata: shared5,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-24",
        event: "events",
        data: {
          event: "on_chain_end",
          data: {
            output: "CopilotKitMiddleware.after_agent",
            input: {
              messages: [
                {
                  id: "id-3",
                  content: "Hi",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                },
                {
                  content: "Hello! How can I assist you today?",
                  additional_kwargs: {},
                  response_metadata: {
                    model_provider: "openai",
                    usage: {
                      prompt_tokens: 8,
                      completion_tokens: 9,
                      total_tokens: 17,
                    },
                  },
                  tool_call_chunks: [],
                  tool_calls: [],
                  id: "id-15",
                  usage_metadata: {
                    input_tokens: 8,
                    output_tokens: 9,
                    total_tokens: 17,
                    input_token_details: {},
                    output_token_details: {},
                  },
                  invalid_tool_calls: [],
                  name: "model",
                  type: "ai",
                },
              ],
              copilotkit: {
                actions: [],
              },
            },
          },
          run_id: "id-23",
          name: "RunnableLambda",
          tags: [],
          metadata: shared5,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-25",
        event: "events",
        data: {
          event: "on_chain_end",
          data: shared1,
          run_id: "id-20",
          name: "CopilotKitMiddleware.after_model",
          tags: ["graph:step:3"],
          metadata: shared5,
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-26",
        event: "events",
        data: {
          event: "on_chain_start",
          data: shared8,
          name: "CopilotKitMiddleware.after_agent",
          tags: ["graph:step:4"],
          run_id: "id-27",
          metadata: shared6,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-29",
        event: "events",
        data: {
          event: "on_chain_end",
          data: shared1,
          run_id: "id-27",
          name: "CopilotKitMiddleware.after_agent",
          tags: ["graph:step:4"],
          metadata: shared6,
        },
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
      rawEvent: {
        id: "id-30",
        event: "events",
        data: {
          event: "on_chain_end",
          data: {
            output: {
              messages: [
                {
                  id: "id-3",
                  content: "Hi",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                },
                {
                  content: "Hello! How can I assist you today?",
                  additional_kwargs: {},
                  response_metadata: {
                    model_provider: "openai",
                    usage: {
                      prompt_tokens: 8,
                      completion_tokens: 9,
                      total_tokens: 17,
                    },
                  },
                  tool_call_chunks: [],
                  tool_calls: [],
                  id: "id-15",
                  usage_metadata: {
                    input_tokens: 8,
                    output_tokens: 9,
                    total_tokens: 17,
                    input_token_details: {},
                    output_token_details: {},
                  },
                  invalid_tool_calls: [],
                  name: "model",
                  type: "ai",
                },
              ],
              copilotkit: {
                actions: [],
              },
            },
          },
          run_id: "id-6",
          name: "LangGraph",
          tags: [],
          metadata: {
            ls_integration: "langgraph",
            created_by: "system",
            graph_id: "agentic_chat",
            assistant_id: "af77e4cd-2160-599e-9a20-86b1cdc1b3c7",
            run_attempt: 1,
            langgraph_version: "<langgraph-version>",
            langgraph_plan: "developer",
            langgraph_host: "self-hosted",
            langgraph_api_url: "<langgraph-api-url>",
            thread_id: "id-1",
            run_id: "id-6",
          },
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 8,
                completion_tokens: 9,
                total_tokens: 17,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-15",
            usage_metadata: {
              input_tokens: 8,
              output_tokens: 9,
              total_tokens: 17,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            name: "model",
            type: "ai",
          },
        ],
        copilotkit: {
          actions: [],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-15",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-6",
    },
  ],
});
