/**
 * The C# emitter: wire model in, the AGUI.Protobuf mappers out.
 *
 * Emits the .NET translation layer between the AGUI.Abstractions models and
 * the protoc-generated C# types (Grpc.Tools compiles those from the same
 * .proto files at build time). The event mapper is field-driven from the wire
 * model; the tables in this file are .NET idiom — which model class carries a
 * definition, which property name deviates from PascalCase, where a model
 * keeps a non-nullable string with an empty default — never field meaning.
 *
 * Every event in the envelope maps to a model class, subagent events included.
 */

import type { Definition, Field, ObjectDefinition, TypeExpr } from "./ir";
import {
  NULLABLE_REQUIRED_ANY,
  NULLABLE_REQUIRED_STRINGS,
  PROP_NAME,
} from "./dotnet-idioms";
import { buildScanGraph } from "./protobuf";
import type { WireModel } from "./protobuf";

/* ------------------------------------------------------------------ */
/* .NET idiom tables                                                    */
/* ------------------------------------------------------------------ */

// PROP_NAME, NULLABLE_REQUIRED_STRINGS and NULLABLE_REQUIRED_ANY live in
// dotnet-idioms.ts: the model emitter declares those properties and these
// mappers carry them, so the two have to read one table rather than two copies
// that can drift apart — a divergence here produces exactly the bare
// ArgumentNullException the nullable-strings table exists to prevent.

/**
 * The union-valued event fields the wire flattens into sibling fields, each with
 * bespoke encode and decode below. A union field not named here has no mapping
 * at all, which is a generator gap rather than a shape the wire omits.
 */
const FLATTENED_UNION_FIELDS = new Set([
  "RunFinishedEvent.outcome",
  "SubagentFinishedEvent.outcome",
]);

function pascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function propertyOf(definitionName: string, field: Field): string {
  return PROP_NAME[`${definitionName}.${field.name}`] ?? pascalCase(field.name);
}

function banner(schemaId: string): string {
  return [
    "// <auto-generated />",
    "// @generated by spec/generator — DO NOT EDIT.",
    `// Source: ${schemaId}`,
    "// Regenerate: pnpm --filter @ag-ui/spec generate",
    "#nullable enable",
  ].join("\n");
}

/* ------------------------------------------------------------------ */
/* Event mapper                                                        */
/* ------------------------------------------------------------------ */

type Kind =
  | "requiredString"
  | "nullableRequiredString"
  | "optionalString"
  | "requiredInt"
  | "optionalInt"
  | "requiredBool"
  | "optionalBool"
  | "requiredAny"
  | "nullableRequiredAny"
  | "optionalAny"
  | "openMap"
  | "patchArray"
  | "messageArray"
  | "usageArray"
  | "interruptArray"
  | "stringArray"
  | "inputMessage"
  | "content"
  | "skip";

interface EventFieldPlan {
  field: Field;
  property: string;
  wireProperty: string;
  kind: Kind;
  /** Closed value set (literal / string enum), enforced on decode. */
  allowed?: string[];
}

function resolveAlias(defs: Map<string, Definition>, type: TypeExpr): TypeExpr {
  while (type.kind === "ref") {
    const target = defs.get(type.name);
    if (target?.kind !== "alias") return type;
    type = target.type;
  }
  return type;
}

/**
 * The closed value set of a literal or string-enum typed field. The wire
 * carries plain strings, so decode has to enforce the set itself — the
 * TypeScript validators reject out-of-set values and this runtime must too.
 */
function allowedValues(
  defs: Map<string, Definition>,
  field: Field,
): string[] | undefined {
  const resolved = resolveAlias(defs, field.type);
  if (resolved.kind === "literal") return [resolved.value];
  if (resolved.kind === "stringEnum") return resolved.values;
  if (resolved.kind === "ref") {
    const target = defs.get(resolved.name);
    if (target?.kind === "enum") return target.values;
  }
  return undefined;
}

function classify(
  defs: Map<string, Definition>,
  definitionName: string,
  field: Field,
): Kind {
  const key = `${definitionName}.${field.name}`;
  const resolved = resolveAlias(defs, field.type);
  switch (resolved.kind) {
    case "string":
    case "literal":
    case "stringEnum":
      if (field.required) {
        return NULLABLE_REQUIRED_STRINGS.has(key)
          ? "nullableRequiredString"
          : "requiredString";
      }
      return "optionalString";
    case "integer":
      return field.required ? "requiredInt" : "optionalInt";
    case "boolean":
      return field.required ? "requiredBool" : "optionalBool";
    case "any":
      if (!field.required) return "optionalAny";
      return NULLABLE_REQUIRED_ANY.has(key)
        ? "nullableRequiredAny"
        : "requiredAny";
    case "openMap":
      return "openMap";
    case "union": {
      // The one inline union the wire carries on an event: content that is a
      // string or a parts array, split by protobuf.ts exactly as on the merged
      // Message. Anything else in this position is a transport decision nobody
      // has made yet.
      const variants = resolved.members;
      const isContent =
        variants.length === 2 &&
        variants.some((variant) => variant.kind === "string") &&
        variants.some(
          (variant) =>
            variant.kind === "array" &&
            variant.items.kind === "ref" &&
            variant.items.name === "ContentPart",
        );
      if (!isContent) {
        throw new Error(
          `${key} is an inline union that is not string | ContentPart[], which ` +
            "the .NET protobuf mappers cannot carry — decide how it rides before regenerating",
        );
      }
      return "content";
    }
    case "array": {
      const items =
        resolved.items.kind === "ref"
          ? defs.get(resolved.items.name)
          : undefined;
      if (items?.name === "JsonPatchOperation" || items?.name === "Message") {
        // Both encode by enumerating the model's list and decode by adding into
        // it, which a nullable property (an optional array) supports in neither
        // direction. No such field exists today; one would need the mappers
        // taught first.
        if (!field.required) {
          throw new Error(
            `${key} is an optional ${items.name} array, which the .NET protobuf ` +
              "mappers cannot carry — make it required or teach the mappers the " +
              "nullable form",
          );
        }
        return items.name === "Message" ? "messageArray" : "patchArray";
      }
      if (items?.name === "TokenUsage") {
        // AddUsage writes nothing for an absent list and BuildUsage answers an
        // empty repeated field with null, both of which a required list would
        // contradict. No such field exists today.
        if (field.required) {
          throw new Error(
            `${key} is a required TokenUsage array, which the .NET protobuf mappers ` +
              "read as absent-or-null — make it optional or teach the mappers the " +
              "required form",
          );
        }
        return "usageArray";
      }
      if (items?.name === "Interrupt") return "interruptArray";
      return "stringArray";
    }
    case "ref": {
      const target = defs.get(resolved.name);
      if (target?.kind === "enum") {
        // Enums ride the wire as strings.
        return field.required ? "requiredString" : "optionalString";
      }
      if (target?.name === "RunAgentInput") return "inputMessage";
      throw new Error(`no .NET mapping for ${key} -> ${resolved.name}`);
    }
    default:
      throw new Error(`no .NET mapping for ${key}`);
  }
}

function encodeField(
  plan: EventFieldPlan,
  proto: string,
  model: string,
  eventTypeConstant: string,
): string[] {
  const p = `${proto}.${plan.wireProperty}`;
  const m = `${model}.${plan.property}`;
  switch (plan.kind) {
    case "requiredString":
      return [`${p} = ${m};`];
    case "nullableRequiredString":
      return [
        `RequireProvided(${m}, "${plan.field.name}", ${eventTypeConstant});`,
        `${p} = ${m}!;`,
      ];
    case "optionalString":
      return [`if (${m} is not null)`, `{`, `    ${p} = ${m};`, `}`];
    case "requiredInt":
    case "requiredBool":
      return [`${p} = ${m};`];
    case "optionalInt":
    case "optionalBool":
      return [`if (${m}.HasValue)`, `{`, `    ${p} = ${m}.Value;`, `}`];
    case "requiredAny":
      return [`${p} = ProtoValueConverter.ToValue(${m});`];
    case "nullableRequiredAny":
      // Required on the wire: a C#-null model value still writes a JSON null,
      // so a decoder that insists on the field's presence (the TypeScript
      // validators do) can read it.
      return [
        `${p} = ${m} is null`,
        `    ? new Google.Protobuf.WellKnownTypes.Value { NullValue = Google.Protobuf.WellKnownTypes.NullValue.NullValue }`,
        `    : ProtoValueConverter.ToValue(${m}.Value);`,
      ];
    case "optionalAny":
      return [
        `if (${m} is not null)`,
        `{`,
        `    ${p} = ProtoValueConverter.ToValue(${m}.Value);`,
        `}`,
      ];
    case "openMap":
      return [`${p} = ProtoValueConverter.ToStructOrNull(${m});`];
    case "patchArray":
      return [
        `if (${m}.ValueKind == JsonValueKind.Array)`,
        `{`,
        `    foreach (var operation in ${m}.EnumerateArray())`,
        `    {`,
        `        ${p}.Add(ProtoMessageMapper.ToProtoPatchOperation(operation));`,
        `    }`,
        `}`,
      ];
    case "messageArray":
      return [
        `foreach (var message in ${m})`,
        `{`,
        `    ${p}.Add(ProtoMessageMapper.ToProto(message));`,
        `}`,
      ];
    case "usageArray":
      return [`AddUsage(${p}, ${m});`];
    case "inputMessage":
      return [
        `if (${m} is not null)`,
        `{`,
        `    ${p} = ProtoMessageMapper.ToProtoRunAgentInput(${m});`,
        `}`,
      ];
    case "content":
      // A string keeps the field; parts take the repeated field beside it,
      // the same split the merged Message uses for its content.
      return [
        `if (${m}.Value is IList<AGUIInputContent> ${plan.property.toLowerCase()}Parts)`,
        `{`,
        `    foreach (var part in ${plan.property.toLowerCase()}Parts)`,
        `    {`,
        `        ${p}Parts.Add(ProtoMessageMapper.ToProtoContentPart(part));`,
        `    }`,
        `}`,
        `else`,
        `{`,
        `    ${p} = ${m}.Value as string ?? string.Empty;`,
        `}`,
      ];
    case "skip":
      return [];
    default:
      throw new Error(
        `encode: unhandled kind ${plan.kind} for ${plan.property} ` +
          `(the schema's ${plan.field.name})`,
      );
  }
}

function decodeField(plan: EventFieldPlan, proto: string): string | undefined {
  const p = `${proto}.${plan.wireProperty}`;
  // Literal / string-enum fields reject out-of-set wire values, matching the
  // TypeScript validators.
  const guarded = (value: string): string =>
    plan.allowed
      ? `AssertOneOf(${value}, "${plan.field.name}", ${plan.allowed
          .map((entry) => JSON.stringify(entry))
          .join(", ")})`
      : value;
  switch (plan.kind) {
    case "requiredString":
    case "nullableRequiredString":
      return `${plan.property} = ${guarded(p)},`;
    case "optionalString":
      return `${plan.property} = ${proto}.Has${plan.wireProperty} ? ${guarded(p)} : null,`;
    case "requiredInt":
    case "requiredBool":
      return `${plan.property} = ${p},`;
    case "optionalInt":
    case "optionalBool":
      return `${plan.property} = ${proto}.Has${plan.wireProperty} ? ${p} : null,`;
    case "requiredAny":
    case "nullableRequiredAny":
      // Required on the wire: an absent Value message is malformed (an
      // explicit JSON null rides as a non-null Value with null_value set).
      return `${plan.property} = ${p} is null ? throw MissingRequiredField("${plan.field.name}") : ProtoValueConverter.ToJsonElement(${p}),`;
    case "optionalAny":
      return `${plan.property} = ProtoValueConverter.ToJsonElementOrNull(${p}),`;
    case "openMap":
      // A required record must be present on the wire, as on the JSON path.
      return plan.field.required
        ? `${plan.property} = ProtoValueConverter.StructToJsonElementOrNull(${p}) ?? throw MissingRequiredField("${plan.field.name}"),`
        : `${plan.property} = ProtoValueConverter.StructToJsonElementOrNull(${p}),`;
    case "usageArray":
      return `${plan.property} = BuildUsage(${p}),`;
    case "inputMessage":
      return plan.field.required
        ? `${plan.property} = ${p} is null ? throw MissingRequiredField("${plan.field.name}") : ProtoMessageMapper.FromProtoRunAgentInput(${p}),`
        : `${plan.property} = ${p} is null ? null : ProtoMessageMapper.FromProtoRunAgentInput(${p}),`;
    case "content":
      return `${plan.property} = ProtoMessageMapper.FromProtoContent(${proto}.Has${plan.wireProperty}, ${p}, ${p}Parts),`;
    case "skip":
      return undefined;
    // Not an initializer, but not unhandled either: both are decoded by the
    // loop that follows the object initializer, because a repeated field is
    // added into rather than assigned.
    case "messageArray":
    case "patchArray":
      return undefined;
    default:
      // Same as encodeField's default, deliberately: a kind only one half of
      // the pair knows about is a field that crosses the wire in one direction
      // and silently vanishes in the other.
      throw new Error(
        `decode: unhandled kind ${plan.kind} for ${plan.property} ` +
          `(the schema's ${plan.field.name})`,
      );
  }
}

/**
 * What the hand-written parts of these mappers cover, field by field. The
 * message role switch, the flattened outcome branches and the input-content
 * arms are prose, not field-driven emission, so a field the schema gains
 * changes nothing in the generated output: the drift gate stays green while the
 * new field silently fails to cross the wire.
 *
 * This table is the contract. Every entry is a field the prose below maps in
 * both directions, pinned with the required-ness and resolved kind the prose
 * assumes: a schema that stops matching it fails generation, with the message
 * saying what changed and where to go and map it.
 */
const MAPPED_FIELDS: Record<string, Record<string, string>> = {
  DeveloperMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(developer)",
    name: "optional string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
    content: "required string",
  },
  SystemMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(system)",
    name: "optional string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
    content: "required string",
  },
  AssistantMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(assistant)",
    name: "optional string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
    content: "optional string",
    toolCalls: "optional ToolCall[]",
  },
  UserMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(user)",
    name: "optional string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
    content: "required union",
  },
  ToolMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(tool)",
    content: "required union",
    toolCallId: "required string",
    error: "optional string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
  },
  ActivityMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(activity)",
    activityType: "required string",
    content: "required openMap",
    metadata: "optional openMap",
  },
  ReasoningMessage: {
    subagentRunId: "optional string",
    id: "required string",
    role: "required literal(reasoning)",
    content: "required string",
    encryptedValue: "optional string",
    metadata: "optional openMap",
  },
  TextPart: {
    type: "required literal(text)",
    id: "optional string",
    text: "required string",
    metadata: "optional any",
  },
  ImagePart: {
    type: "required literal(image)",
    id: "optional string",
    source: "required PartSource",
    metadata: "optional any",
  },
  AudioPart: {
    type: "required literal(audio)",
    id: "optional string",
    source: "required PartSource",
    metadata: "optional any",
  },
  VideoPart: {
    type: "required literal(video)",
    id: "optional string",
    source: "required PartSource",
    metadata: "optional any",
  },
  DocumentPart: {
    type: "required literal(document)",
    id: "optional string",
    source: "required PartSource",
    metadata: "optional any",
  },
  DataSource: {
    type: "required literal(data)",
    value: "required string",
    mimeType: "required string",
  },
  UrlSource: {
    type: "required literal(url)",
    value: "required string",
    mimeType: "optional string",
  },
  FileSource: {
    type: "required literal(file)",
    value: "required string",
    provider: "optional string",
    mimeType: "optional string",
  },
  ToolCall: {
    id: "required string",
    type: "required literal(function)",
    function: "required FunctionCall",
    encryptedValue: "optional string",
    metadata: "optional openMap",
  },
  FunctionCall: {
    name: "required string",
    arguments: "required string",
  },
  Tool: {
    name: "required string",
    description: "required string",
    parameters: "optional any",
    metadata: "optional openMap",
  },
  Context: {
    description: "required string",
    value: "required string",
  },
  Interrupt: {
    subagentRunId: "optional string",
    id: "required string",
    reason: "required string",
    message: "optional string",
    toolCallId: "optional string",
    responseSchema: "optional openMap",
    expiresAt: "optional string",
    metadata: "optional openMap",
  },
  ResumeEntry: {
    interruptId: "required string",
    status: "required enum(resolved|cancelled)",
    payload: "optional any",
    metadata: "optional openMap",
  },
  RunAgentInput: {
    threadId: "required string",
    runId: "required string",
    protocolVersion: "optional string",
    parentRunId: "optional string",
    state: "optional any",
    messages: "required Message[]",
    tools: "optional Tool[]",
    context: "optional Context[]",
    forwardedProps: "optional any",
    resume: "optional ResumeEntry[]",
  },
  RunFinishedSuccessOutcome: {
    type: "required literal(success)",
    pendingToolCallIds: "optional string[]",
  },
  RunFinishedInterruptOutcome: {
    type: "required literal(interrupt)",
    interrupts: "required Interrupt[]",
  },
  RunFinishedCancelledOutcome: {
    type: "required literal(cancelled)",
  },
  SubagentFinishedSuccessOutcome: {
    type: "required literal(success)",
  },
  SubagentFinishedSuspendedOutcome: {
    type: "required literal(suspended)",
    interruptIds: "optional string[]",
  },
  AddOperation: {
    op: "required literal(add)",
    path: "required string",
    value: "required any",
  },
  RemoveOperation: {
    op: "required literal(remove)",
    path: "required string",
  },
  ReplaceOperation: {
    op: "required literal(replace)",
    path: "required string",
    value: "required any",
  },
  MoveOperation: {
    op: "required literal(move)",
    from: "required string",
    path: "required string",
  },
  CopyOperation: {
    op: "required literal(copy)",
    from: "required string",
    path: "required string",
  },
  TestOperation: {
    op: "required literal(test)",
    path: "required string",
    value: "required any",
  },
  BaseEvent: {
    type: "required EventType",
    timestamp: "optional integer",
    rawEvent: "optional any",
    metadata: "optional openMap",
  },
  TokenUsage: {
    provider: "optional string",
    model: "optional string",
    inputTokens: "optional integer",
    outputTokens: "optional integer",
    totalTokens: "optional integer",
    reasoningTokens: "optional integer",
    cachedInputTokens: "optional integer",
    cacheWriteInputTokens: "optional integer",
  },
};

/**
 * The unions whose members the hand-written prose switches over. A member the
 * schema adds needs an arm of its own, which the field inventory below cannot
 * notice on its own: an unmapped member is a missing branch, not a missing
 * field.
 */
const MAPPED_UNIONS = [
  "Message",
  "JsonPatchOperation",
  "ContentPart",
  "PartSource",
  "RunFinishedOutcome",
  "SubagentFinishedOutcome",
];

/**
 * How MAPPED_FIELDS names a field's type: the alias-resolved kind, or the
 * definition a reference lands on, so a field that keeps its name while
 * changing shape does not pass for unchanged.
 */
function describeFieldType(
  defs: Map<string, Definition>,
  type: TypeExpr,
): string {
  const resolved = resolveAlias(defs, type);
  if (resolved.kind === "array") {
    return `${describeFieldType(defs, resolved.items)}[]`;
  }
  if (resolved.kind === "ref") return resolved.name;
  // The vocabulary itself, since the hand-written prose spells the accepted
  // values out (AssertOneOf) and a value the schema adds would otherwise reject
  // there while the models advertise it.
  if (resolved.kind === "literal") return `literal(${resolved.value})`;
  if (resolved.kind === "stringEnum") {
    return `enum(${resolved.values.join("|")})`;
  }
  return resolved.kind;
}

/**
 * Every definition the hand-written mapper prose is responsible for. Mixins are
 * looked up too: BaseEvent is not a definition of its own, but its fields ride
 * every event through the hand-written BuildBaseEvent/ApplyBaseEvent pair.
 */
function assertMappedFieldsMatchTheSchema(
  defs: Map<string, Definition>,
  mixins: ObjectDefinition[],
): void {
  const shapeOf = (name: string): ObjectDefinition | undefined => {
    const definition = defs.get(name);
    if (definition?.kind === "object") return definition;
    return mixins.find((mixin) => mixin.name === name);
  };
  const complaints: string[] = [];
  for (const name of MAPPED_UNIONS) {
    const union = defs.get(name);
    if (union?.kind !== "union") {
      complaints.push(`${name} is no longer a union in the schema`);
      continue;
    }
    const unmapped = union.members.filter(
      (member) => MAPPED_FIELDS[member] === undefined,
    );
    if (unmapped.length > 0) {
      complaints.push(
        `${name} gained the member${unmapped.length === 1 ? "" : "s"} ${unmapped.join(", ")}, ` +
          "which the mapper prose has no arm for",
      );
    }
  }
  for (const [name, mapped] of Object.entries(MAPPED_FIELDS)) {
    const definition = shapeOf(name);
    if (definition === undefined) {
      complaints.push(`${name} is no longer an object in the schema`);
      continue;
    }
    const actual = new Map(
      definition.fields.map((field) => [
        field.name,
        `${field.required ? "required" : "optional"} ${describeFieldType(defs, field.type)}`,
      ]),
    );
    for (const [field, shape] of actual) {
      const pinned = mapped[field];
      if (pinned === undefined) {
        complaints.push(
          `${name} gained ${field}, which the mapper prose does not map`,
        );
      } else if (pinned !== shape) {
        complaints.push(
          `${name}.${field} is now ${shape}, where the mapper prose reads it as ${pinned}`,
        );
      }
    }
    for (const field of Object.keys(mapped)) {
      if (!actual.has(field)) {
        complaints.push(
          `${name} no longer has ${field}, which MAPPED_FIELDS still claims`,
        );
      }
    }
  }
  if (complaints.length > 0) {
    throw new Error(
      `the hand-written protobuf mappers are out of step with the schema: ${complaints.join("; ")} — ` +
        "map the field in ProtoMessageMapper/ProtoEventMapper and update MAPPED_FIELDS",
    );
  }
}

export function emitDotnet(
  wire: WireModel,
): Array<{ name: string; content: string }> {
  const { defs, model } = wire;
  const objectDef = (name: string): ObjectDefinition => {
    const definition = defs.get(name);
    if (definition?.kind !== "object")
      throw new Error(`${name} is not an object`);
    return definition;
  };
  const eventUnion = defs.get("Event");
  if (eventUnion?.kind !== "union") throw new Error("Event union missing");
  const baseNames = new Set(wire.baseFieldNames);

  const eventMessage = wire.messages.find((entry) => entry.name === "Event");
  const envelopeTags = (eventMessage?.oneof?.entries ?? [])
    .map((entry) => entry.number)
    .sort((a, b) => a - b);

  interface EventPlan {
    definition: ObjectDefinition;
    /** The protoc-generated C# names: oneof property and message class. */
    oneofProperty: string;
    protoType: string;
    eventType: string;
    fields: EventFieldPlan[];
  }

  const plans: EventPlan[] = wire.envelope.map((entry) => {
    const definition = objectDef(entry.definition);
    const typeField = definition.fields.find((field) => field.name === "type");
    if (typeField?.type.kind !== "literal") throw new Error("event type field");
    const oneofProperty = entry.entry.split("_").map(pascalCase).join("");
    const fields: EventFieldPlan[] = definition.fields
      .filter((field) => !baseNames.has(field.name))
      .flatMap((field) => {
        // The flattened outcome expands at the wire level; handled bespoke.
        if (
          field.type.kind === "ref" &&
          defs.get(field.type.name)?.kind === "union"
        ) {
          if (!FLATTENED_UNION_FIELDS.has(`${definition.name}.${field.name}`)) {
            throw new Error(
              `${definition.name}.${field.name} is a union the wire flattens, and this ` +
                "emitter has no bespoke encode/decode for it — write one (see BuildOutcome) " +
                "and add the field to FLATTENED_UNION_FIELDS, or the field would silently " +
                "vanish from the .NET protobuf mappers",
            );
          }
          return [];
        }
        const kind = classify(defs, definition.name, field);
        if (kind === "skip") return [];
        return [
          {
            field,
            property: propertyOf(definition.name, field),
            wireProperty: pascalCase(field.name),
            kind,
            allowed: allowedValues(defs, field),
          },
        ];
      });
    return {
      definition,
      oneofProperty,
      protoType: definition.name,
      eventType: typeField.type.value,
      fields,
    };
  });

  /* -------- outcome flattening specs (RunFinished; Subagent skipped) ---- */
  const runFinished = plans.find(
    (plan) => plan.definition.name === "RunFinishedEvent",
  );
  if (!runFinished) throw new Error("RunFinishedEvent missing");

  const encodeCases = plans
    .map((plan) => {
      const name = plan.definition.name;
      const assignments = plan.fields
        .flatMap((field) =>
          encodeField(
            field,
            "proto",
            "e",
            `AGUIEventTypes.${plan.oneofProperty}`,
          ),
        )
        .map((line) => `                ${line}`)
        .join("\n");
      const outcome =
        name === "RunFinishedEvent"
          ? `
                if (e.Outcome is RunFinishedInterruptOutcome interruptOutcome)
                {
                    proto.Outcome = "interrupt";
                    foreach (var interrupt in interruptOutcome.Interrupts)
                    {
                        proto.Interrupts.Add(ProtoMessageMapper.ToProtoInterrupt(interrupt));
                    }
                }
                else if (e.Outcome is RunFinishedSuccessOutcome successOutcome)
                {
                    proto.Outcome = "success";
                    if (successOutcome.PendingToolCallIds is not null)
                    {
                        foreach (var pendingToolCallId in successOutcome.PendingToolCallIds)
                        {
                            proto.PendingToolCallIds.Add(pendingToolCallId);
                        }
                    }
                }
                else if (e.Outcome is RunFinishedCancelledOutcome)
                {
                    proto.Outcome = "cancelled";
                }
                else
                {
                    proto.Outcome = string.Empty;
                }
`
          : name === "SubagentFinishedEvent"
            ? `
                if (e.Outcome is SubagentFinishedSuspendedOutcome suspendedOutcome)
                {
                    proto.Outcome = "suspended";
                    if (suspendedOutcome.InterruptIds is not null)
                    {
                        foreach (var interruptId in suspendedOutcome.InterruptIds)
                        {
                            proto.InterruptIds.Add(interruptId);
                        }
                    }
                }
                else if (e.Outcome is SubagentFinishedSuccessOutcome)
                {
                    proto.Outcome = "success";
                }
                else
                {
                    proto.Outcome = string.Empty;
                }
`
            : "";
      return `            case ${name} e:
            {
                var proto = new Proto.${name}
                {
                    BaseEvent = BuildBaseEvent(e, Proto.EventType.${plan.oneofProperty}),
                };
${assignments}
${outcome}                return new Proto.Event { ${plan.oneofProperty} = proto };
            }`;
    })
    .join("\n");

  const decodeCases = plans
    .map((plan) => {
      const name = plan.definition.name;
      const initializers = plan.fields
        .map((field) => decodeField(field, "e"))
        .filter((line): line is string => line !== undefined)
        .map((line) => `                    ${line}`)
        .join("\n");
      const arrays = plan.fields
        .filter(
          (field) =>
            field.kind === "messageArray" || field.kind === "patchArray",
        )
        .map((field) => field);
      const post = arrays
        .map((field) => {
          if (field.kind === "messageArray") {
            return `                foreach (var message in e.${field.wireProperty})
                {
                    result.${field.property}.Add(ProtoMessageMapper.FromProto(message));
                }`;
          }
          return `                result.${field.property} = BuildPatchArray(e.${field.wireProperty});`;
        })
        .join("\n");
      const outcome =
        name === "RunFinishedEvent"
          ? `                result.Outcome = BuildOutcome(e);\n`
          : name === "SubagentFinishedEvent"
            ? `                result.Outcome = BuildSubagentOutcome(e);\n`
            : "";
      return `            case Proto.Event.EventOneofCase.${plan.oneofProperty}:
            {
                var e = proto.${plan.oneofProperty};
                var result = new ${name}
                {
${initializers}
                };
${post}${post ? "\n" : ""}${outcome}                ApplyBaseEvent(result, e.BaseEvent, Proto.EventType.${plan.oneofProperty});
                return result;
            }`;
    })
    .join("\n");

  const eventMapper = `${banner(model.schemaId)}

using System;
using System.Collections.Generic;
using System.Text.Json;
using AGUI.Abstractions;
using Google.Protobuf.Collections;
using Proto = AGUI.ProtocolBuffers;

namespace AGUI.Protobuf;

// Maps AG-UI .NET events to and from the generated protobuf Event oneof,
// generated from the same wire model as the TypeScript translation so the two
// runtimes cannot drift. Reshaping rules (outcome flattening, patch op<->enum)
// match sdks/typescript/packages/proto/src/proto.ts.
internal static class ProtoEventMapper
{
    public static Proto.Event ToProto(BaseEvent evt)
    {
        switch (evt)
        {
${encodeCases}
            default:
                // An event model outside the schema-derived set: named the same
                // way the JSON writer names one, never encoded as something else.
                throw new AGUIUnknownEventTypeException(
                    $"Event type '{evt.Type}' is not representable in the AG-UI protobuf wire format by this SDK.",
                    evt.Type);
        }
    }

    public static BaseEvent FromProto(Proto.Event proto)
    {
        switch (proto.EventCase)
        {
${decodeCases}
            default:
                // Either an empty envelope or a variant this build was not
                // compiled against; the framed reader skips it, a caller
                // decoding a single event sees it.
                throw new AGUIUnknownEventTypeException(
                    "The protobuf envelope carries no AG-UI event variant this SDK recognises.");
        }
    }

    // A required wire string whose model property is nullable: the protobuf
    // setter rejects null with a bare ArgumentNullException naming only
    // "value", which says nothing about the event or the field. Checks null and
    // not empty — the schemas require the key to be present but accept an empty
    // value, and the property is nullable precisely so the two stay apart.
    private static void RequireProvided(string? value, string propertyName, string eventType)
    {
        if (value is null)
        {
            throw new InvalidOperationException(
                $"Cannot encode '{eventType}': '{propertyName}' is required.");
        }
    }

    private static Proto.BaseEvent BuildBaseEvent(BaseEvent evt, Proto.EventType type)
    {
        var baseEvent = new Proto.BaseEvent { Type = type };

        if (evt.Timestamp.HasValue)
        {
            baseEvent.Timestamp = evt.Timestamp.Value;
        }

        if (evt.RawEvent is not null)
        {
            baseEvent.RawEvent = ProtoValueConverter.ToValue(evt.RawEvent.Value);
        }

        baseEvent.Metadata = ProtoValueConverter.ToStructOrNull(evt.Metadata);

        return baseEvent;
    }

    private static void ApplyBaseEvent(
        BaseEvent target,
        Proto.BaseEvent? baseEvent,
        Proto.EventType expected)
    {
        if (baseEvent is null)
        {
            throw new System.IO.InvalidDataException(
                "Invalid event: the envelope entry carries no base event.");
        }

        // The envelope entry is authoritative; a base event declaring a
        // different type (or an out-of-enum value) is a contradiction another
        // runtime could resolve differently, so it rejects.
        if (baseEvent.Type != expected)
        {
            throw new System.IO.InvalidDataException(
                $"Invalid event: the envelope carries {expected} but the base event says {baseEvent.Type}.");
        }

        if (baseEvent.HasTimestamp)
        {
            target.Timestamp = baseEvent.Timestamp;
        }

        if (baseEvent.RawEvent is not null)
        {
            target.RawEvent = ProtoValueConverter.ToJsonElement(baseEvent.RawEvent);
        }

        target.Metadata = ProtoValueConverter.StructToJsonElementOrNull(baseEvent.Metadata);
    }

    private static RunFinishedOutcome? BuildOutcome(Proto.RunFinishedEvent proto)
    {
        if (proto.Outcome == "interrupt")
        {
            // The schema requires at least one interrupt: an interrupt
            // outcome with nothing to answer would leave a consumer with
            // nothing to do, and the TypeScript validators reject it.
            if (proto.Interrupts.Count == 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: interrupt outcome carries no interrupts.");
            }

            // Pending tool call ids belong to the success outcome: an
            // interrupted run names what it waits for through its interrupts.
            if (proto.PendingToolCallIds.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: outcome interrupt cannot carry pendingToolCallIds.");
            }

            var outcome = new RunFinishedInterruptOutcome();
            foreach (var interrupt in proto.Interrupts)
            {
                outcome.Interrupts.Add(ProtoMessageMapper.FromProtoInterrupt(interrupt));
            }

            return outcome;
        }

        if (proto.Outcome == "success")
        {
            // A success (or absent) outcome carrying interrupts is a
            // contradiction: a consumer branching on the discriminator would
            // finish the run with an interrupt still pending.
            if (proto.Interrupts.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: outcome success cannot carry interrupts.");
            }

            var outcome = new RunFinishedSuccessOutcome();
            if (proto.PendingToolCallIds.Count > 0)
            {
                outcome.PendingToolCallIds = new List<string>(proto.PendingToolCallIds);
            }

            return outcome;
        }

        if (proto.Outcome == "cancelled")
        {
            // A cancelled run waits for nothing, so interrupts beside it are
            // the same contradiction as beside success.
            if (proto.Interrupts.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: outcome cancelled cannot carry interrupts.");
            }

            return new RunFinishedCancelledOutcome();
        }

        if (proto.Outcome.Length == 0)
        {
            if (proto.Interrupts.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: absent outcome cannot carry interrupts.");
            }

            if (proto.PendingToolCallIds.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: absent outcome cannot carry pendingToolCallIds.");
            }

            return null;
        }

        // An unknown discriminator must not silently decode to "no outcome",
        // which would imply success; the JSON path errors on it too.
        throw new System.IO.InvalidDataException(
            $"Invalid event: unknown outcome '{proto.Outcome}'.");
    }

    private static SubagentFinishedOutcome? BuildSubagentOutcome(Proto.SubagentFinishedEvent proto)
    {
        if (proto.Outcome == "suspended")
        {
            var outcome = new SubagentFinishedSuspendedOutcome();
            if (proto.InterruptIds.Count > 0)
            {
                outcome.InterruptIds = new List<string>(proto.InterruptIds);
            }

            return outcome;
        }

        if (proto.Outcome == "success")
        {
            // A success (or absent) outcome carrying interrupt ids is a
            // contradiction: the subagent finished, so nothing is pending.
            if (proto.InterruptIds.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: outcome success cannot carry interruptIds.");
            }

            return new SubagentFinishedSuccessOutcome();
        }

        if (proto.Outcome.Length == 0)
        {
            if (proto.InterruptIds.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: absent outcome cannot carry interruptIds.");
            }

            return null;
        }

        // An unknown discriminator must not silently decode to "no outcome",
        // which would imply success; the JSON path errors on it too.
        throw new System.IO.InvalidDataException(
            $"Invalid event: unknown outcome '{proto.Outcome}'.");
    }

    // Token usage maps 1:1 onto the repeated Usage field. An absent list and an
    // empty list both encode to zero entries, so legacy events (no usage) stay
    // byte-for-byte identical on the wire; decoding mirrors that by returning
    // null rather than an empty list.
    private static void AddUsage(RepeatedField<Proto.Usage> target, IList<TokenUsage>? usage)
    {
        if (usage is null)
        {
            return;
        }

        foreach (var entry in usage)
        {
            var proto = new Proto.Usage();
            if (entry.Provider is not null)
            {
                proto.Provider = entry.Provider;
            }

            if (entry.Model is not null)
            {
                proto.Model = entry.Model;
            }

            if (entry.InputTokens is { } inputTokens)
            {
                proto.InputTokens = inputTokens;
            }

            if (entry.OutputTokens is { } outputTokens)
            {
                proto.OutputTokens = outputTokens;
            }

            if (entry.TotalTokens is { } totalTokens)
            {
                proto.TotalTokens = totalTokens;
            }

            if (entry.ReasoningTokens is { } reasoningTokens)
            {
                proto.ReasoningTokens = reasoningTokens;
            }

            if (entry.CachedInputTokens is { } cachedInputTokens)
            {
                proto.CachedInputTokens = cachedInputTokens;
            }

            if (entry.CacheWriteInputTokens is { } cacheWriteInputTokens)
            {
                proto.CacheWriteInputTokens = cacheWriteInputTokens;
            }

            target.Add(proto);
        }
    }

    private static IList<TokenUsage>? BuildUsage(RepeatedField<Proto.Usage> usage)
    {
        if (usage.Count == 0)
        {
            return null;
        }

        var result = new List<TokenUsage>(usage.Count);
        foreach (var entry in usage)
        {
            result.Add(new TokenUsage
            {
                Provider = entry.HasProvider ? entry.Provider : null,
                Model = entry.HasModel ? entry.Model : null,
                InputTokens = entry.HasInputTokens ? entry.InputTokens : null,
                OutputTokens = entry.HasOutputTokens ? entry.OutputTokens : null,
                TotalTokens = entry.HasTotalTokens ? entry.TotalTokens : null,
                ReasoningTokens = entry.HasReasoningTokens ? entry.ReasoningTokens : null,
                CachedInputTokens = entry.HasCachedInputTokens ? entry.CachedInputTokens : null,
                CacheWriteInputTokens = entry.HasCacheWriteInputTokens ? entry.CacheWriteInputTokens : null,
            });
        }

        return result;
    }

    internal static string AssertOneOf(string value, string field, params string[] allowed)
    {
        foreach (var entry in allowed)
        {
            if (value == entry)
            {
                return value;
            }
        }

        throw new System.IO.InvalidDataException(
            $"Invalid event: {field} carries unknown value '{value}'.");
    }

    internal static System.IO.InvalidDataException MissingRequiredField(string field)
        => new($"Invalid event: required field '{field}' is missing.");

    private static JsonElement BuildPatchArray(RepeatedField<Proto.JsonPatchOperation> operations)
    {
        return JsonElementFactory.Create(writer =>
        {
            writer.WriteStartArray();
            foreach (var operation in operations)
            {
                ProtoMessageMapper.WriteProtoPatchOperation(writer, operation);
            }

            writer.WriteEndArray();
        });
    }
}
`;

  /* ------------------------------------------------------------------ */
  /* Wire guards                                                          */
  /* ------------------------------------------------------------------ */

  // The malformed-wire scan preserves the distinct-oneof-arm checks. Repeated
  // occurrences of the same message field are left to protobuf's normal merge.
  // Closed sets for the bespoke message-mapper guards, read from the schema
  // so the values can never drift from it.
  const closedSet = (definitionName: string, fieldName: string): string => {
    const definition = objectDef(definitionName);
    const field = definition.fields.find((entry) => entry.name === fieldName);
    if (!field) throw new Error(`${definitionName}.${fieldName} missing`);
    const values = allowedValues(defs, field);
    if (!values)
      throw new Error(`${definitionName}.${fieldName} is not closed`);
    return values.map((value) => JSON.stringify(value)).join(", ");
  };

  const scanGraph = buildScanGraph(wire);

  const scanMethods = scanGraph.specs
    .map((spec) => {
      const armNumbers = spec.arms?.numbers ?? [];
      const nestedCases = spec.descend
        .map(
          (entry) =>
            `                            case ${entry.number}:
                                Scan${entry.child}(data.Slice(offset, (int)length));
                                break;`,
        )
        .join("\n");
      const armCheck =
        armNumbers.length === 0
          ? ""
          : `
                        if (${armNumbers
                          .map((n) => `field == ${n}`)
                          .join(" || ")})
                        {
                            if (seenArm != 0 && seenArm != field)
                            {
                                throw new InvalidDataException(
                                    "Invalid event: ${spec.arms?.name} carries more than one arm.");
                            }

                            seenArm = field;
                        }
`;
      const locals = [
        armNumbers.length > 0 ? "        uint seenArm = 0;\n" : "",
      ].join("");
      return `    private static void Scan${spec.name}(ReadOnlySpan<byte> data)
    {
        int offset = 0;
        int groupDepth = 0;
${locals}
        while (offset < data.Length)
        {
            uint tag = ReadVarint(data, ref offset);
            uint field = tag / 8;
            uint wireType = tag % 8;

            if (field == 0)
            {
                throw new InvalidDataException("Invalid event: field zero is not a legal tag.");
            }

            if (wireType == 3)
            {
                groupDepth += 1;
                continue;
            }

            if (wireType == 4)
            {
                groupDepth -= 1;
                if (groupDepth < 0)
                {
                    throw new InvalidDataException("Invalid event: unbalanced group.");
                }

                continue;
            }

            switch (wireType)
            {
                case 0:
                    ReadVarint(data, ref offset);
                    break;
                case 1:
                    offset += 8;
                    break;
                case 2:
                {
                    uint length = ReadVarint(data, ref offset);
                    if (offset + (long)length > data.Length)
                    {
                        throw new InvalidDataException("Invalid event: truncated payload.");
                    }

                    if (groupDepth == 0)
                    {
${armCheck}                        switch (field)
                        {
${nestedCases || "                            default:\n                                break;"}
                        }
                    }

                    offset += (int)length;
                    break;
                }
                case 5:
                    offset += 4;
                    break;
                default:
                    throw new InvalidDataException("Invalid event: unknown wire type.");
            }

            if (offset > data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated payload.");
            }
        }

        if (groupDepth != 0)
        {
            throw new InvalidDataException("Invalid event: unbalanced group.");
        }
    }`;
    })
    .join("\n\n");

  const envelopeScanCases = scanGraph.envelope
    .map(
      (entry) =>
        `                        case ${entry.number}:
                            Scan${entry.child}(data.Slice(offset, (int)length));
                            break;`,
    )
    .join("\n");

  const wireGuards = `${banner(model.schemaId)}

using System;
using System.IO;

namespace AGUI.Protobuf;

// The envelope pre-scan, generated from the same wire model as the
// TypeScript scan: different known event kinds in one envelope are rejected.
// Repeated occurrences of one kind use protobuf's normal merge behavior.
// Unknown field numbers are protobuf's to ignore,
// repeated or not, so forward compatibility is untouched. Field zero is not a
// legal tag. Legacy group fields nest and are skipped wholesale.
internal static class WireGuards
{
    private static readonly bool[] KnownEnvelopeTags = BuildKnownTags();

    private static bool[] BuildKnownTags()
    {
        var known = new bool[${Math.max(...envelopeTags) + 1}];
${envelopeTags.map((tag) => `        known[${tag}] = true;`).join("\n")}
        return known;
    }

    /// <summary>
    /// Rejects an envelope whose malformed shape would decode differently across runtimes,
    /// and reports whether what it carries could be an event newer than this build.
    /// </summary>
    /// <returns>
    /// <see langword="true"/> only when the envelope names no event this build knows and
    /// carries at least one unknown length-delimited field — the shape every event arm of
    /// the envelope has, and so the only shape a newer runtime's event can arrive in.
    /// Anything else that leaves the decoder without an event is broken bytes rather than
    /// a variant from the future, and the two are answered differently.
    /// </returns>
    public static bool AssertWellFormedEnvelope(ReadOnlySpan<byte> data)
    {
        int knownTags = 0;
        uint knownEventField = 0;
        int unknownEventArms = 0;
        int offset = 0;
        int groupDepth = 0;

        while (offset < data.Length)
        {
            uint tag = ReadVarint(data, ref offset);
            uint field = tag / 8;
            uint wireType = tag % 8;

            if (field == 0)
            {
                throw new InvalidDataException("Invalid event: field zero is not a legal tag.");
            }

            if (wireType == 3)
            {
                // A group carrying a known event's field number still names that
                // event, and counting it keeps a decoder that finds no readable
                // event from mistaking these bytes for an event from the future.
                if (groupDepth == 0 && field < (uint)KnownEnvelopeTags.Length && KnownEnvelopeTags[(int)field])
                {
                    knownTags += 1;
                }

                groupDepth += 1;
                continue;
            }

            if (wireType == 4)
            {
                groupDepth -= 1;
                if (groupDepth < 0)
                {
                    throw new InvalidDataException("Invalid event: unbalanced group.");
                }

                continue;
            }

            if (groupDepth == 0 && field < (uint)KnownEnvelopeTags.Length && KnownEnvelopeTags[(int)field])
            {
                // Repeated occurrences of the same event merge. A different
                // known event kind still violates the envelope's contract.
                if (knownEventField != 0 && knownEventField != field)
                {
                    throw new InvalidDataException(
                        "Invalid event: the envelope carries more than one event.");
                }

                knownTags += 1;
                knownEventField = field;
            }

            switch (wireType)
            {
                case 0:
                    ReadVarint(data, ref offset);
                    break;
                case 1:
                    offset += 8;
                    break;
                case 2:
                {
                    // Two statements on purpose: adding the call inline would
                    // capture offset before the varint advances it.
                    uint length = ReadVarint(data, ref offset);
                    if (offset + (long)length > data.Length)
                    {
                        throw new InvalidDataException("Invalid event: truncated payload.");
                    }

                    if (groupDepth == 0
                        && (field >= (uint)KnownEnvelopeTags.Length || !KnownEnvelopeTags[(int)field]))
                    {
                        // A length-delimited field this build does not know is
                        // the shape a newer runtime's event arrives in.
                        unknownEventArms += 1;
                    }

                    if (groupDepth == 0)
                    {
                        // Events that can carry a nested oneof get their
                        // payload scanned for arm exclusivity too.
                        switch (field)
                        {
${envelopeScanCases}
                            default:
                                break;
                        }
                    }

                    offset += (int)length;
                    break;
                }
                case 5:
                    offset += 4;
                    break;
                default:
                    throw new InvalidDataException("Invalid event: unknown wire type.");
            }

            if (offset > data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated payload.");
            }
        }

        if (groupDepth != 0)
        {
            throw new InvalidDataException("Invalid event: unbalanced group.");
        }

        return knownTags == 0 && unknownEventArms > 0;
    }

    // The nested scans, one message level each, generated from the shared
    // scan graph. A oneof carrying more than one distinct arm in an occurrence
    // rejects. Repeated message fields merge through the standard parser.
    // google.protobuf.* payloads remain outside the guard's traversal.
${scanMethods}

    // Mirrors the uint32 reader truncation exactly: the fifth byte contributes
    // only its low four bits, later bytes none — otherwise an overlong tag
    // encoding would dodge duplicate detection while the real decoder still
    // reads the canonical field number.
    private static uint ReadVarint(ReadOnlySpan<byte> data, ref int offset)
    {
        uint result = 0;
        int shift = 0;
        while (true)
        {
            if (offset >= data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated varint.");
            }

            byte value = data[offset++];
            if (shift < 28)
            {
                result += (uint)(value & 0x7f) << shift;
            }
            else if (shift == 28)
            {
                result += (uint)(value & 0x0f) << 28;
            }

            shift += 7;
            if ((value & 0x80) == 0)
            {
                return result;
            }
        }
    }
}
`;

  /* ------------------------------------------------------------------ */
  /* Message mapper                                                       */
  /* ------------------------------------------------------------------ */

  const messageUnion = defs.get("Message");
  if (messageUnion?.kind !== "union") throw new Error("Message union missing");

  const messageMapper = `${banner(model.schemaId)}

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using AGUI.Abstractions;
using Google.Protobuf.WellKnownTypes;
using Proto = AGUI.ProtocolBuffers;

namespace AGUI.Protobuf;

// Maps the AG-UI .NET message/content/tool-call/interrupt/json-patch/input
// model to and from the generated protobuf messages, generated from the same
// wire model as the TypeScript translation.
internal static class ProtoMessageMapper
{
    public static Proto.Message ToProto(AGUIMessage message)
    {
        var proto = new Proto.Message
        {
            Id = message.Id ?? string.Empty,
            Role = message.Role,
            Metadata = ProtoValueConverter.ToStructOrNull(message.Metadata),
        };

        if (message.SubagentRunId is not null)
        {
            proto.SubagentRunId = message.SubagentRunId;
        }

        switch (message)
        {
            case AGUIUserMessage user:
                if (user.Name is not null)
                {
                    proto.Name = user.Name;
                }

                if (user.EncryptedValue is not null)
                {
                    proto.EncryptedValue = user.EncryptedValue;
                }

                if (user.Content.Value is IList<AGUIInputContent> parts)
                {
                    foreach (var part in parts)
                    {
                        proto.ContentParts.Add(ToProtoContentPart(part));
                    }
                }
                else if (user.Content.Value is string text)
                {
                    proto.Content = text;
                }
                else
                {
                    proto.Content = string.Empty;
                }

                break;
            case AGUIAssistantMessage assistant:
                if (assistant.Content is not null)
                {
                    proto.Content = assistant.Content;
                }

                if (assistant.Name is not null)
                {
                    proto.Name = assistant.Name;
                }

                if (assistant.EncryptedValue is not null)
                {
                    proto.EncryptedValue = assistant.EncryptedValue;
                }

                if (assistant.ToolCalls is not null)
                {
                    foreach (var toolCall in assistant.ToolCalls)
                    {
                        proto.ToolCalls.Add(ToProtoToolCall(toolCall));
                    }
                }

                break;
            case AGUISystemMessage system:
                proto.Content = system.Content;
                if (system.Name is not null)
                {
                    proto.Name = system.Name;
                }

                if (system.EncryptedValue is not null)
                {
                    proto.EncryptedValue = system.EncryptedValue;
                }

                break;
            case AGUIDeveloperMessage developer:
                proto.Content = developer.Content;
                if (developer.Name is not null)
                {
                    proto.Name = developer.Name;
                }

                if (developer.EncryptedValue is not null)
                {
                    proto.EncryptedValue = developer.EncryptedValue;
                }

                break;
            case AGUIToolMessage tool:
                if (tool.Content.Value is IList<AGUIInputContent> toolParts)
                {
                    foreach (var part in toolParts)
                    {
                        proto.ContentParts.Add(ToProtoContentPart(part));
                    }
                }
                else
                {
                    proto.Content = tool.Content.Value as string ?? string.Empty;
                }

                proto.ToolCallId = tool.ToolCallId;
                if (tool.Error is not null)
                {
                    proto.Error = tool.Error;
                }

                if (tool.EncryptedValue is not null)
                {
                    proto.EncryptedValue = tool.EncryptedValue;
                }

                break;
            case AGUIActivityMessage activity:
                proto.ActivityType = activity.ActivityType;
                proto.ActivityContent = ProtoValueConverter.ToStructOrNull(activity.Content);
                break;
            case AGUIReasoningMessage reasoning:
                proto.Content = reasoning.Content;
                if (reasoning.EncryptedValue is not null)
                {
                    proto.EncryptedValue = reasoning.EncryptedValue;
                }

                break;
            default:
                throw new NotSupportedException(
                    $"Message role '{message.Role}' is not supported by the AG-UI protobuf wire format.");
        }

        return proto;
    }

    public static AGUIMessage FromProto(Proto.Message proto)
    {
        AssertRoleExclusiveCarriers(proto);
        var message = FromProtoCore(proto);
        message.Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata);
        message.SubagentRunId = proto.HasSubagentRunId ? proto.SubagentRunId : null;
        return message;
    }

    // Content carriers are role-exclusive; a message carrying a carrier its
    // role does not use would lose data whichever one decode preferred.
    private static void AssertRoleExclusiveCarriers(Proto.Message proto)
    {
        bool isActivity = proto.Role == AGUIRoles.Activity;
        // The roles whose content is a string or a parts array: the user's, and
        // the tool's since tool results learned to carry parts.
        bool carriesParts = proto.Role == AGUIRoles.User || proto.Role == AGUIRoles.Tool;

        if (proto.ActivityContent is not null && !isActivity)
        {
            throw new InvalidDataException(
                "Invalid event: message carries activity content for a non-activity role.");
        }

        if (isActivity && (proto.HasContent || proto.ContentParts.Count > 0))
        {
            throw new InvalidDataException(
                "Invalid event: activity content cannot ride with other content forms.");
        }

        if (!carriesParts && proto.ContentParts.Count > 0)
        {
            throw new InvalidDataException(
                "Invalid event: message carries content parts for a role that has none.");
        }

        if (carriesParts && proto.HasContent && proto.ContentParts.Count > 0)
        {
            throw new InvalidDataException(
                "Invalid event: message carries both string content and content parts.");
        }
    }

    private static AGUIMessage FromProtoCore(Proto.Message proto)
    {
        // An empty id is schema-valid and the wire cannot carry an absent one
        // (the field is required), so empty stays empty — as in TypeScript.
        var id = proto.Id;

        switch (proto.Role)
        {
            case AGUIRoles.User:
            {
                var user = new AGUIUserMessage
                {
                    Id = id,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };

                user.Content = FromProtoContent(proto.HasContent, proto.Content, proto.ContentParts);

                return user;
            }
            case AGUIRoles.Assistant:
            {
                var assistant = new AGUIAssistantMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : null,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };

                if (proto.ToolCalls.Count > 0)
                {
                    var toolCalls = new List<AGUIToolCall>();
                    foreach (var protoToolCall in proto.ToolCalls)
                    {
                        toolCalls.Add(FromProtoToolCall(protoToolCall));
                    }

                    assistant.ToolCalls = toolCalls;
                }

                return assistant;
            }
            case AGUIRoles.System:
                return new AGUISystemMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Developer:
                return new AGUIDeveloperMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Tool:
                return new AGUIToolMessage
                {
                    Id = id,
                    Content = FromProtoContent(proto.HasContent, proto.Content, proto.ContentParts),
                    ToolCallId = proto.HasToolCallId ? proto.ToolCallId : string.Empty,
                    Error = proto.HasError ? proto.Error : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Activity:
                return new AGUIActivityMessage
                {
                    Id = id,
                    ActivityType = proto.HasActivityType ? proto.ActivityType : string.Empty,
                    Content = ProtoValueConverter.StructToJsonElementOrNull(proto.ActivityContent)
                        ?? throw ProtoEventMapper.MissingRequiredField("content"),
                };
            case AGUIRoles.Reasoning:
                return new AGUIReasoningMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            default:
                throw new NotSupportedException(
                    $"Message role '{proto.Role}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    public static Proto.RunAgentInput ToProtoRunAgentInput(RunAgentInput input)
    {
        var proto = new Proto.RunAgentInput
        {
            ThreadId = input.ThreadId,
            RunId = input.RunId,
        };

        if (input.ProtocolVersion is not null)
        {
            proto.ProtocolVersion = input.ProtocolVersion;
        }

        if (input.ParentRunId is not null)
        {
            proto.ParentRunId = input.ParentRunId;
        }

        if (input.State is not null)
        {
            proto.State = ProtoValueConverter.ToValue(input.State.Value);
        }

        foreach (var message in input.Messages)
        {
            proto.Messages.Add(ToProto(message));
        }

        if (input.Tools is not null)
        {
            foreach (var tool in input.Tools)
            {
                proto.Tools.Add(ToProtoTool(tool));
            }
        }

        if (input.Context is not null)
        {
            foreach (var context in input.Context)
            {
                proto.Context.Add(new Proto.Context
                {
                    Description = context.Description,
                    Value = context.Value,
                });
            }
        }

        if (input.ForwardedProperties is not null)
        {
            proto.ForwardedProps = ProtoValueConverter.ToValue(input.ForwardedProperties.Value);
        }

        if (input.Resume is not null)
        {
            foreach (var resume in input.Resume)
            {
                proto.Resume.Add(ToProtoResume(resume));
            }
        }

        return proto;
    }

    public static RunAgentInput FromProtoRunAgentInput(Proto.RunAgentInput proto)
    {
        var input = new RunAgentInput
        {
            ThreadId = proto.ThreadId,
            RunId = proto.RunId,
            ProtocolVersion = proto.HasProtocolVersion ? proto.ProtocolVersion : null,
            ParentRunId = proto.HasParentRunId ? proto.ParentRunId : null,
            State = ProtoValueConverter.ToJsonElementOrNull(proto.State),
            ForwardedProperties = ProtoValueConverter.ToJsonElementOrNull(proto.ForwardedProps),
        };

        foreach (var message in proto.Messages)
        {
            input.Messages.Add(FromProto(message));
        }

        // The wire cannot tell an absent array from an empty one; present-empty
        // is the one form every layer accepts.
        var tools = new List<AGUITool>(proto.Tools.Count);
        foreach (var tool in proto.Tools)
        {
            tools.Add(FromProtoTool(tool));
        }

        input.Tools = tools;

        var contexts = new List<AGUIContext>(proto.Context.Count);
        foreach (var context in proto.Context)
        {
            contexts.Add(new AGUIContext { Description = context.Description, Value = context.Value });
        }

        input.Context = contexts;

        var resumes = new List<AGUIResume>(proto.Resume.Count);
        foreach (var resume in proto.Resume)
        {
            resumes.Add(FromProtoResume(resume));
        }

        input.Resume = resumes;

        return input;
    }

    private static Proto.Tool ToProtoTool(AGUITool tool)
    {
        var proto = new Proto.Tool
        {
            Name = tool.Name,
            Description = tool.Description,
            Metadata = ProtoValueConverter.ToStructOrNull(tool.Metadata),
        };

        if (tool.Parameters is not null)
        {
            proto.Parameters = ProtoValueConverter.ToValue(tool.Parameters.Value);
        }

        return proto;
    }

    private static AGUITool FromProtoTool(Proto.Tool proto)
    {
        return new AGUITool
        {
            Name = proto.Name,
            Description = proto.Description,
            Parameters = ProtoValueConverter.ToJsonElementOrNull(proto.Parameters),
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    private static Proto.ResumeEntry ToProtoResume(AGUIResume resume)
    {
        var proto = new Proto.ResumeEntry
        {
            InterruptId = resume.InterruptId,
            Status = resume.Status,
            Metadata = ProtoValueConverter.ToStructOrNull(resume.Metadata),
        };

        if (resume.Payload is not null)
        {
            proto.Payload = ProtoValueConverter.ToValue(resume.Payload.Value);
        }

        return proto;
    }

    private static AGUIResume FromProtoResume(Proto.ResumeEntry proto)
    {
        return new AGUIResume
        {
            InterruptId = proto.InterruptId,
            Status = ProtoEventMapper.AssertOneOf(proto.Status, "status", ${closedSet("ResumeEntry", "status")}),
            Payload = ProtoValueConverter.ToJsonElementOrNull(proto.Payload),
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    public static Proto.ToolCall ToProtoToolCall(AGUIToolCall toolCall)
    {
        var proto = new Proto.ToolCall
        {
            Id = toolCall.Id,
            Type = toolCall.Type,
            Metadata = ProtoValueConverter.ToStructOrNull(toolCall.Metadata),
            Function = new Proto.ToolCall.Types.Function
            {
                Name = toolCall.Function.Name,
                Arguments = toolCall.Function.Arguments,
            },
        };

        if (toolCall.EncryptedValue is not null)
        {
            proto.EncryptedValue = toolCall.EncryptedValue;
        }

        return proto;
    }

    public static AGUIToolCall FromProtoToolCall(Proto.ToolCall proto)
    {
        if (proto.Function is null)
        {
            throw ProtoEventMapper.MissingRequiredField("function");
        }

        return new AGUIToolCall
        {
            Id = proto.Id,
            Type = ProtoEventMapper.AssertOneOf(proto.Type, "type", ${closedSet("ToolCall", "type")}),
            Function = new AGUIToolCallFunction
            {
                Name = proto.Function.Name,
                Arguments = proto.Function.Arguments,
            },
            EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    public static Proto.Interrupt ToProtoInterrupt(AGUIInterrupt interrupt)
    {
        var proto = new Proto.Interrupt
        {
            Id = interrupt.Id,
            Reason = interrupt.Reason,
        };

        if (interrupt.Message is not null)
        {
            proto.Message = interrupt.Message;
        }

        if (interrupt.ToolCallId is not null)
        {
            proto.ToolCallId = interrupt.ToolCallId;
        }

        if (interrupt.ResponseSchema is not null)
        {
            proto.ResponseSchema = ProtoValueConverter.ToValue(interrupt.ResponseSchema.Value);
        }

        if (interrupt.ExpiresAt is not null)
        {
            proto.ExpiresAt = interrupt.ExpiresAt;
        }

        if (interrupt.Metadata is not null)
        {
            proto.Metadata = ProtoValueConverter.ToValue(interrupt.Metadata.Value);
        }

        if (interrupt.SubagentRunId is not null)
        {
            proto.SubagentRunId = interrupt.SubagentRunId;
        }

        return proto;
    }

    public static AGUIInterrupt FromProtoInterrupt(Proto.Interrupt proto)
    {
        return new AGUIInterrupt
        {
            Id = proto.Id,
            Reason = proto.Reason,
            Message = proto.HasMessage ? proto.Message : null,
            ToolCallId = proto.HasToolCallId ? proto.ToolCallId : null,
            ResponseSchema = ProtoValueConverter.ToJsonElementOrNull(proto.ResponseSchema),
            ExpiresAt = proto.HasExpiresAt ? proto.ExpiresAt : null,
            Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Metadata),
            SubagentRunId = proto.HasSubagentRunId ? proto.SubagentRunId : null,
        };
    }

    public static Proto.JsonPatchOperation ToProtoPatchOperation(JsonElement operation)
    {
        var proto = new Proto.JsonPatchOperation
        {
            Op = ParseOperationType(GetStringProperty(operation, "op")),
            Path = GetStringProperty(operation, "path") ?? string.Empty,
        };

        if (operation.TryGetProperty("from", out var from) && from.ValueKind == JsonValueKind.String)
        {
            proto.From = from.GetString() ?? string.Empty;
        }

        if (operation.TryGetProperty("value", out var value) && value.ValueKind != JsonValueKind.Undefined)
        {
            proto.Value = ProtoValueConverter.ToValue(value);
        }

        return proto;
    }

    public static void WriteProtoPatchOperation(Utf8JsonWriter writer, Proto.JsonPatchOperation proto)
    {
        writer.WriteStartObject();
        writer.WriteString("op", OperationTypeToString(proto.Op));
        writer.WriteString("path", proto.Path);

        if (proto.HasFrom)
        {
            writer.WriteString("from", proto.From);
        }

        if (proto.Value is not null)
        {
            writer.WritePropertyName("value");
            ProtoValueConverter.WriteValue(writer, proto.Value);
        }

        writer.WriteEndObject();
    }

    /// <summary>
    /// Reads string-or-parts content off its two wire fields. String content
    /// rides the content field; anything else is the parts array — including
    /// an empty one, which is valid content of its own. A part with no
    /// recognisable arm is rejected, not erased.
    /// </summary>
    internal static AGUIContent FromProtoContent(
        bool hasContent,
        string content,
        Google.Protobuf.Collections.RepeatedField<Proto.InputContent> protoParts)
    {
        if (hasContent && protoParts.Count > 0)
        {
            // String content and parts together is a contradiction the encoder
            // never writes; resolving it either way would silently discard the
            // other half. The TypeScript translation rejects the same packet.
            throw new InvalidDataException(
                "Invalid event: content carries both string content and content parts.");
        }

        if (hasContent)
        {
            return content;
        }

        var parts = new List<AGUIInputContent>();
        foreach (var protoPart in protoParts)
        {
            var part = FromProtoContentPart(protoPart);
            if (part is null)
            {
                throw new InvalidDataException(
                    "Invalid event: unreadable content part.");
            }

            parts.Add(part);
        }

        return parts;
    }

    internal static Proto.InputContent ToProtoContentPart(AGUIInputContent part)
    {
        switch (part)
        {
            case AGUITextInputContent text:
            {
                var wire = new Proto.TextInputPart
                {
                    Text = text.Text,
                    Metadata = ProtoValueConverter.ToValueOrNull(text.Metadata),
                };
                if (text.Id is not null)
                {
                    wire.Id = text.Id;
                }

                return new Proto.InputContent { Text = wire };
            }
            case AGUIImageInputContent image:
            {
                var wire = new Proto.ImageInputPart
                {
                    Source = ToProtoSource(image.Source),
                    Metadata = ProtoValueConverter.ToValueOrNull(image.Metadata),
                };
                if (image.Id is not null)
                {
                    wire.Id = image.Id;
                }

                return new Proto.InputContent { Image = wire };
            }
            case AGUIAudioInputContent audio:
            {
                var wire = new Proto.AudioInputPart
                {
                    Source = ToProtoSource(audio.Source),
                    Metadata = ProtoValueConverter.ToValueOrNull(audio.Metadata),
                };
                if (audio.Id is not null)
                {
                    wire.Id = audio.Id;
                }

                return new Proto.InputContent { Audio = wire };
            }
            case AGUIVideoInputContent video:
            {
                var wire = new Proto.VideoInputPart
                {
                    Source = ToProtoSource(video.Source),
                    Metadata = ProtoValueConverter.ToValueOrNull(video.Metadata),
                };
                if (video.Id is not null)
                {
                    wire.Id = video.Id;
                }

                return new Proto.InputContent { Video = wire };
            }
            case AGUIDocumentInputContent document:
            {
                var wire = new Proto.DocumentInputPart
                {
                    Source = ToProtoSource(document.Source),
                    Metadata = ProtoValueConverter.ToValueOrNull(document.Metadata),
                };
                if (document.Id is not null)
                {
                    wire.Id = document.Id;
                }

                return new Proto.InputContent { Document = wire };
            }
            default:
                // A part the wire has no arm for: dropping it would delete what
                // the message says, which the TypeScript translation refuses too.
                throw new NotSupportedException(
                    $"Input content part '{part.Type}' is not representable in the AG-UI protobuf wire format by this SDK.");
        }
    }

    private static AGUIInputContent? FromProtoContentPart(Proto.InputContent proto)
    {
        switch (proto.PartCase)
        {
            case Proto.InputContent.PartOneofCase.Text:
                return new AGUITextInputContent
                {
                    Id = proto.Text.HasId ? proto.Text.Id : null,
                    Text = proto.Text.Text,
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Text.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Image:
                return new AGUIImageInputContent
                {
                    Id = proto.Image.HasId ? proto.Image.Id : null,
                    Source = RequireSource(FromProtoSource(proto.Image.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Image.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Audio:
                return new AGUIAudioInputContent
                {
                    Id = proto.Audio.HasId ? proto.Audio.Id : null,
                    Source = RequireSource(FromProtoSource(proto.Audio.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Audio.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Video:
                return new AGUIVideoInputContent
                {
                    Id = proto.Video.HasId ? proto.Video.Id : null,
                    Source = RequireSource(FromProtoSource(proto.Video.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Video.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Document:
                return new AGUIDocumentInputContent
                {
                    Id = proto.Document.HasId ? proto.Document.Id : null,
                    Source = RequireSource(FromProtoSource(proto.Document.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Document.Metadata),
                };
            case Proto.InputContent.PartOneofCase.None:
            default:
                return null;
        }
    }

    private static AGUIInputContentSource RequireSource(AGUIInputContentSource? source)
    {
        return source ?? throw new InvalidDataException(
            "Invalid event: a media content part carries no readable source.");
    }

    private static Proto.InputContentSource ToProtoSource(AGUIInputContentSource source)
    {
        switch (source)
        {
            case AGUIInputContentDataSource data:
                return new Proto.InputContentSource
                {
                    Data = new Proto.InputContentDataSource
                    {
                        Value = data.Value,
                        MimeType = data.MimeType,
                    },
                };
            case AGUIInputContentUrlSource url:
            {
                var urlSource = new Proto.InputContentUrlSource { Value = url.Value };
                if (url.MimeType is not null)
                {
                    urlSource.MimeType = url.MimeType;
                }

                return new Proto.InputContentSource { Url = urlSource };
            }
            case AGUIInputContentFileSource file:
            {
                var fileSource = new Proto.InputContentFileSource { Value = file.Value };
                if (file.Provider is not null)
                {
                    fileSource.Provider = file.Provider;
                }

                if (file.MimeType is not null)
                {
                    fileSource.MimeType = file.MimeType;
                }

                return new Proto.InputContentSource { File = fileSource };
            }
            default:
                throw new NotSupportedException(
                    $"Input content source type '{source.Type}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    private static AGUIInputContentSource? FromProtoSource(Proto.InputContentSource? source)
    {
        if (source is null)
        {
            return null;
        }

        switch (source.SourceCase)
        {
            case Proto.InputContentSource.SourceOneofCase.Data:
                return new AGUIInputContentDataSource
                {
                    Value = source.Data.Value,
                    MimeType = source.Data.MimeType,
                };
            case Proto.InputContentSource.SourceOneofCase.Url:
                return new AGUIInputContentUrlSource
                {
                    Value = source.Url.Value,
                    MimeType = source.Url.HasMimeType ? source.Url.MimeType : null,
                };
            case Proto.InputContentSource.SourceOneofCase.File:
                return new AGUIInputContentFileSource
                {
                    Value = source.File.Value,
                    Provider = source.File.HasProvider ? source.File.Provider : null,
                    MimeType = source.File.HasMimeType ? source.File.MimeType : null,
                };
            case Proto.InputContentSource.SourceOneofCase.None:
            default:
                return null;
        }
    }

    private static Proto.JsonPatchOperationType ParseOperationType(string? op)
    {
        switch (op)
        {
${(defs.get("JsonPatchOperation") as { members: string[] }).members
  .map((member) => {
    const memberDef = objectDef(member);
    const discriminator = memberDef.fields.find((field) => field.name === "op");
    if (discriminator?.type.kind !== "literal") throw new Error("op literal");
    const value = discriminator.type.value;
    return `            case "${value}":
                return Proto.JsonPatchOperationType.${pascalCase(value)};`;
  })
  .join("\n")}
            default:
                throw new NotSupportedException(
                    $"JSON Patch operation '{op}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    private static string OperationTypeToString(Proto.JsonPatchOperationType op)
    {
        switch (op)
        {
${(defs.get("JsonPatchOperation") as { members: string[] }).members
  .map((member) => {
    const memberDef = objectDef(member);
    const discriminator = memberDef.fields.find((field) => field.name === "op");
    if (discriminator?.type.kind !== "literal") throw new Error("op literal");
    const value = discriminator.type.value;
    return `            case Proto.JsonPatchOperationType.${pascalCase(value)}:
                return "${value}";`;
  })
  .join("\n")}
            default:
                // A wire value outside the enum must not invent an operation.
                throw new InvalidDataException(
                    $"Invalid event: unknown patch operation '{(int)op}'.");
        }
    }

    private static string? GetStringProperty(JsonElement element, string name)
    {
        if (element.ValueKind == JsonValueKind.Object &&
            element.TryGetProperty(name, out var value) &&
            value.ValueKind == JsonValueKind.String)
        {
            return value.GetString();
        }

        return null;
    }
}
`;

  assertMappedFieldsMatchTheSchema(defs, model.mixinShapes);

  return [
    { name: "ProtoEventMapper.g.cs", content: eventMapper },
    { name: "ProtoMessageMapper.g.cs", content: messageMapper },
    { name: "WireGuards.g.cs", content: wireGuards },
  ];
}
