// @generated by spec/generator — DO NOT EDIT.
// Source: https://ag-ui.com/spec/1.0/schema.json
// Regenerate: pnpm --filter @ag-ui/spec generate

import { BaseEvent, AGUIEvent, EventType, omitOptionalNulls } from "@ag-ui/core";
import { EventSchemas } from "@ag-ui/core/schemas";
import * as protoEvents from "./generated/events";
import * as protoPatch from "./generated/patch";
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/**
 * These converters run against values that have crossed a wire boundary, so
 * they accept `unknown` and narrow once rather than trusting a static type.
 */
type LooseRecord = Record<string, unknown>;

const asRecord = (value: unknown): LooseRecord | undefined =>
  value && typeof value === "object" ? (value as LooseRecord) : undefined;

const asArray = (value: unknown): unknown[] => (Array.isArray(value) ? value : []);

/**
 * The same switch the client's enforcement stage reads, so one variable
 * silences both halves of what is really one decision about unrecognised
 * material.
 */
const suppressWarnings = (): boolean =>
  typeof process !== "undefined" &&
  typeof process.env !== "undefined" &&
  Boolean(process.env.SUPPRESS_TRANSFORMATION_WARNINGS);

/**
 * The one drop this layer makes that it cannot hand on to enforcement.
 *
 * An unrecognised role or patch operation still has a NAME — the string or the
 * enum value arrived on the wire — so it rides along and enforcement strips it
 * and says which path it stripped. An unset protobuf oneof has no name at all:
 * the bytes say only that no arm this build knows was populated. There is
 * nothing to pass on, so the drop has to happen here, and a drop that happens
 * here is a drop enforcement will never mention. Saying so is the difference
 * between the two transports losing the same part loudly and one of them
 * losing it in silence.
 */
const warnDroppedContentPart = (): void => {
  if (suppressWarnings()) return;
  console.warn(
    "[ag-ui][proto] Dropped a content part this build does not know: the protocol has a variant this SDK predates.",
  );
};

/**
 * The encode-side twin, and the only one that can say WHERE.
 *
 * Reached only with validation bypassed, since the schema would have rejected
 * the part first. There is no wire arm to put it on, so it cannot be encoded —
 * but the message then arrives at the far end one part shorter, and until this
 * warning existed nothing said which part went missing or from which message.
 */
const warnUnencodableContentPart = (at: string, index: number): void => {
  if (suppressWarnings()) return;
  console.warn(
    `[ag-ui][proto.encode] Dropped ${at}.${CONTENT_FIELD}[${index}]: no wire form for this content part, so it is not encoded.`,
  );
};

function toCamelCase(str: string): string {
  return str.toLowerCase().replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
}

/**
 * A validation failure as the list of places it failed.
 *
 * Read structurally rather than by instanceof: a zod error crossing a package
 * boundary may come from a different copy of zod, and an instanceof that
 * quietly missed would leave the warning naming nothing at all.
 */
const issuePaths = (err: unknown): string => {
  const issues = (err as { issues?: unknown })?.issues;
  if (!Array.isArray(issues) || issues.length === 0) return String(err);
  const paths = issues.map((issue) => {
    const path = (issue as { path?: unknown }).path;
    return Array.isArray(path) && path.length > 0 ? `/${path.join("/")}` : "the event itself";
  });
  return [...new Set(paths)].join(", ");
};

/**
 * The event types the handwritten SDK models know. The schema — and this
 * generated wire layer — can be ahead of them; an event outside this set is
 * carried structurally and validated once the SDK catches up.
 */
const KNOWN_TO_CORE = new Set<string>(Object.values(EventType));

/**
 * The envelope's oneof entry names, mapped to the event type each carries.
 * The entry selected the message shape, so it is authoritative on decode.
 */
const ENVELOPE_TYPE: Record<string, string | undefined> = {
  textMessageStart: "TEXT_MESSAGE_START",
  textMessageContent: "TEXT_MESSAGE_CONTENT",
  textMessageEnd: "TEXT_MESSAGE_END",
  textMessageChunk: "TEXT_MESSAGE_CHUNK",
  toolCallStart: "TOOL_CALL_START",
  toolCallArgs: "TOOL_CALL_ARGS",
  toolCallEnd: "TOOL_CALL_END",
  toolCallChunk: "TOOL_CALL_CHUNK",
  toolCallResult: "TOOL_CALL_RESULT",
  stateSnapshot: "STATE_SNAPSHOT",
  stateDelta: "STATE_DELTA",
  messagesSnapshot: "MESSAGES_SNAPSHOT",
  activitySnapshot: "ACTIVITY_SNAPSHOT",
  activityDelta: "ACTIVITY_DELTA",
  raw: "RAW",
  custom: "CUSTOM",
  runStarted: "RUN_STARTED",
  runFinished: "RUN_FINISHED",
  runError: "RUN_ERROR",
  stepStarted: "STEP_STARTED",
  stepFinished: "STEP_FINISHED",
  reasoningStart: "REASONING_START",
  reasoningMessageStart: "REASONING_MESSAGE_START",
  reasoningMessageContent: "REASONING_MESSAGE_CONTENT",
  reasoningMessageEnd: "REASONING_MESSAGE_END",
  reasoningMessageChunk: "REASONING_MESSAGE_CHUNK",
  reasoningEnd: "REASONING_END",
  reasoningEncryptedValue: "REASONING_ENCRYPTED_VALUE",
  subagentStarted: "SUBAGENT_STARTED",
  subagentFinished: "SUBAGENT_FINISHED",
  subagentError: "SUBAGENT_ERROR",
};
/** The envelope's known field numbers, for the repeated-tag scan. */
const ENVELOPE_TAGS = new Set<number>([
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
  28, 29, 30, 31,
]);

/**
 * Narrows metadata to the object the wire format declares, or nothing.
 *
 * On the validated path the schema has already guaranteed this. On the fallback
 * path below the event is unvalidated, and the generated `Struct.wrap` would
 * quietly mangle anything else — an array becomes `{"0": …}`, a string becomes
 * per-character keys, a number becomes `{}`. Dropping the value is the honest
 * outcome for a shim whose contract is to warn and encode best-effort; the
 * caller already gets a loud warning naming the validation failure.
 */
const normalizeMetadata = (metadata: unknown): LooseRecord | undefined =>
  typeof metadata === "object" && metadata !== null && !Array.isArray(metadata)
    ? (metadata as LooseRecord)
    : undefined;

const toProtoSource = (source: unknown): unknown => {
  const rec = asRecord(source);
  if (!rec) return undefined;
  if (rec.type === "data") {
    return { data: { value: rec.value, mimeType: rec.mimeType } };
  }
  if (rec.type === "url") {
    return { url: { value: rec.value, mimeType: rec.mimeType } };
  }
  if (rec.type === "file") {
    return { file: { value: rec.value, provider: rec.provider, mimeType: rec.mimeType } };
  }
  return undefined;
};

const fromProtoSource = (source: unknown): unknown => {
  const rec = asRecord(source);
  if (!rec) return undefined;
  // Exactly one populated arm: a source carrying several is malformed, and
  // picking one would silently discard the rest.
  if ([rec.data, rec.url, rec.file].filter(Boolean).length > 1) {
    throw new Error("Invalid event: source carries more than one arm");
  }
  if (rec.data) {
    const wire = rec.data as LooseRecord;
    return { type: "data", value: wire.value, mimeType: wire.mimeType };
  }
  if (rec.url) {
    const wire = rec.url as LooseRecord;
    return { type: "url", value: wire.value, mimeType: wire.mimeType };
  }
  if (rec.file) {
    const wire = rec.file as LooseRecord;
    return { type: "file", value: wire.value, provider: wire.provider, mimeType: wire.mimeType };
  }
  return undefined;
};

const toProtoContentPart = (part: unknown): unknown => {
  const rec = asRecord(part);
  if (!rec) return undefined;

  switch (rec.type) {
    case "text":
      return { text: { id: rec.id, text: rec.text, metadata: rec.metadata } };
    case "image":
      return { image: { id: rec.id, source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "audio":
      return { audio: { id: rec.id, source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "video":
      return { video: { id: rec.id, source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "document":
      return {
        document: { id: rec.id, source: toProtoSource(rec.source), metadata: rec.metadata },
      };
    // Legacy compatibility, predating the schema: the retired "binary" part
    // rides as a document part with marker metadata. Behavioural rule of this
    // layer, not a schema fact.
    case "binary": {
      const source = rec.data
        ? { data: { value: rec.data, mimeType: rec.mimeType } }
        : rec.url
          ? { url: { value: rec.url, mimeType: rec.mimeType } }
          : rec.id
            ? { url: { value: rec.id, mimeType: rec.mimeType } }
            : undefined;
      if (!source) return undefined;
      return {
        document: {
          source,
          metadata: { legacyBinary: true, filename: rec.filename, id: rec.id },
        },
      };
    }
    default:
      return undefined;
  }
};

const fromProtoContentPart = (part: unknown): unknown => {
  const rec = asRecord(part);
  if (!rec) return undefined;
  // Exactly one populated arm, as with the source above.
  if ([rec.text, rec.image, rec.audio, rec.video, rec.document].filter(Boolean).length > 1) {
    throw new Error("Invalid event: content part carries more than one arm");
  }
  if (rec.text) {
    const part = rec.text as LooseRecord;
    return { type: "text", id: part.id, text: part.text, metadata: part.metadata };
  }
  if (rec.image) {
    const part = rec.image as LooseRecord;
    if (part.source !== undefined && fromProtoSource(part.source) === undefined) {
      return undefined;
    }
    return {
      type: "image",
      id: part.id,
      source: fromProtoSource(part.source),
      metadata: part.metadata,
    };
  }
  if (rec.audio) {
    const part = rec.audio as LooseRecord;
    if (part.source !== undefined && fromProtoSource(part.source) === undefined) {
      return undefined;
    }
    return {
      type: "audio",
      id: part.id,
      source: fromProtoSource(part.source),
      metadata: part.metadata,
    };
  }
  if (rec.video) {
    const part = rec.video as LooseRecord;
    if (part.source !== undefined && fromProtoSource(part.source) === undefined) {
      return undefined;
    }
    return {
      type: "video",
      id: part.id,
      source: fromProtoSource(part.source),
      metadata: part.metadata,
    };
  }
  if (rec.document) {
    const part = rec.document as LooseRecord;
    if (part.source !== undefined && fromProtoSource(part.source) === undefined) {
      return undefined;
    }
    return {
      type: "document",
      id: part.id,
      source: fromProtoSource(part.source),
      metadata: part.metadata,
    };
  }
  return undefined;
};

/**
 * The wire's one Message carries the union of every role's fields; which
 * field feeds `content` depends on the role.
 */
const MAP_CONTENT_ROLES = new Set<string>(["activity"]);
const PARTS_CONTENT_ROLES = new Set<string>(["user", "tool"]);
/** Every role the Message union declares, for telling unknown from misused. */
const KNOWN_ROLES = new Set<string>([
  "developer",
  "system",
  "assistant",
  "user",
  "tool",
  "activity",
  "reasoning",
]);

/** The JSON field the merged Message splits, for naming a part in a warning. */
const CONTENT_FIELD = "content";

const toWireMessage = (value: unknown, at = "message"): LooseRecord => {
  const message = asRecord(value) ?? {};
  const wire: LooseRecord = { ...message, contentParts: [] };
  wire.metadata = normalizeMetadata(message.metadata);
  wire.toolCalls = asArray(message.toolCalls).map((toolCall: unknown) => ({
    ...(toolCall as LooseRecord),
    metadata: normalizeMetadata(asRecord(toolCall)?.metadata),
  }));
  if (Array.isArray(message.content)) {
    wire.contentParts = message.content
      .map((part: unknown, index: number) => {
        const mapped = toProtoContentPart(part);
        if (mapped === undefined) warnUnencodableContentPart(at, index);
        return mapped;
      })
      .filter((part: unknown) => part !== undefined);
    wire.content = undefined;
  } else if (typeof message.role === "string" && MAP_CONTENT_ROLES.has(message.role)) {
    wire.activityContent = normalizeMetadata(message.content) ?? {};
    wire.content = undefined;
  }
  return wire;
};

const fromWireMessage = (value: unknown): LooseRecord | undefined => {
  const wire = asRecord(value) ?? {};
  const message: LooseRecord = { ...wire };
  const role = typeof wire.role === "string" ? wire.role : "";
  // A role this build does not know makes the whole message an unrecognised
  // member of the Message union — which is exactly what the same message is on
  // the JSON path, where enforcement's discriminated-union walk removes it from
  // the array and NAMES the path it removed. So it is rebuilt as it arrived and
  // judged there, on both transports alike. Dropping it here instead removed it
  // just as surely, but silently: enforcement then saw a snapshot with nothing
  // wrong in it, and the same stream lost a message loudly over SSE and quietly
  // over protobuf.
  const known = KNOWN_ROLES.has(role);
  // Which carrier feeds `content` is a fact about the ROLE, for a role this
  // build knows. For one it does not, there is no rule to look up and no way to
  // invent one, so the carrier the producer actually populated decides.
  // An unknown role's EMPTY parts array reads as no content — enforcement drops the message anyway.
  const usesParts = known ? PARTS_CONTENT_ROLES.has(role) : asArray(wire.contentParts).length > 0;
  const usesMap = known
    ? MAP_CONTENT_ROLES.has(role)
    : !usesParts && wire.activityContent !== undefined;
  // Carrier exclusivity comes in two kinds, and only one of them survives not
  // knowing the role.
  //
  // WHICH carrier a role uses is a fact about the role, so it can only be
  // checked for a role this build knows; applying it to an unknown one would
  // make a role added after this build shipped fatal over binary and
  // survivable over SSE — the very split this layer exists to prevent.
  //
  // Carrying SEVERAL at once is different: they are competing spellings of one
  // JSON field, so no role, present or future, can mean anything by it. That
  // half holds whatever the role is. Without it an unknown role carrying two
  // would have kept whichever this code happened to read first and dropped the
  // rest in silence — the same quiet loss this whole change is about.
  if (
    !known &&
    (wire.content !== undefined ? 1 : 0) +
      (asArray(wire.contentParts).length > 0 ? 1 : 0) +
      (wire.activityContent !== undefined ? 1 : 0) >
      1
  ) {
    throw new Error("Invalid event: message carries more than one content form");
  }
  if (known) {
    // Content carriers are role-exclusive; a message carrying a carrier its
    // role does not use would lose data whichever one decode preferred.
    if (!usesParts && asArray(wire.contentParts).length > 0) {
      throw new Error("Invalid event: message carries content parts for a role that has none");
    }
    if (wire.activityContent !== undefined && !usesMap) {
      throw new Error("Invalid event: message carries activity content for a non-activity role");
    }
    if (usesMap && wire.content !== undefined) {
      throw new Error("Invalid event: activity content cannot ride with other content forms");
    }
    if (usesParts && wire.content !== undefined && asArray(wire.contentParts).length > 0) {
      // String content and parts together is a contradiction the encoder never
      // writes; resolving it either way would silently discard the other half.
      throw new Error("Invalid event: message carries both string content and content parts");
    }
  }
  if (usesParts && wire.content === undefined) {
    // String content rides the content field; anything else is the parts
    // array — including an empty one, which is valid content of its own. A
    // part naming no arm this build knows is DROPPED rather than rejected,
    // because that is what the same part does on the JSON path: an
    // unrecognised member of a union is stripped from its array, and a media
    // kind added after this build shipped must not kill the message carrying
    // it. Rejecting here made a future content part fatal over binary and
    // survivable over SSE.
    message.content = asArray(wire.contentParts)
      .map((part: unknown) => {
        const mapped = fromProtoContentPart(part);
        if (mapped === undefined) warnDroppedContentPart();
        return mapped;
      })
      .filter((part: unknown) => part !== undefined);
  }
  if (usesMap && wire.activityContent !== undefined) {
    message.content = wire.activityContent;
  }
  delete message.activityContent;
  delete message.contentParts;
  if (asArray(wire.toolCalls).length === 0) {
    delete message.toolCalls;
  }
  Object.keys(message).forEach((key) => {
    if (message[key] === undefined) delete message[key];
  });
  return message;
};

/**
 * ts-proto materialises absent optional fields as undefined-valued keys, on
 * nested objects too. An absent field stays absent: the keys go.
 */
const dropUndefinedDeep = (value: unknown): void => {
  if (Array.isArray(value)) {
    for (const entry of value) dropUndefinedDeep(entry);
    return;
  }
  const rec = asRecord(value);
  if (!rec) return;
  for (const key of Object.keys(rec)) {
    if (rec[key] === undefined) {
      delete rec[key];
    } else {
      dropUndefinedDeep(rec[key]);
    }
  }
};

const normalizeItemMetadata = (value: unknown): LooseRecord => ({
  ...(asRecord(value) ?? {}),
  metadata: normalizeMetadata(asRecord(value)?.metadata),
});

const toWireRunAgentInput = (value: unknown): LooseRecord | undefined => {
  const input = asRecord(value);
  if (!input) return undefined;
  return {
    threadId: input.threadId,
    runId: input.runId,
    protocolVersion: input.protocolVersion,
    parentRunId: input.parentRunId,
    state: input.state,
    messages: asArray(input.messages).map((item: unknown, index: number) =>
      toWireMessage(item, `messages[${index}]`),
    ),
    tools: asArray(input.tools).map(normalizeItemMetadata),
    context: asArray(input.context),
    forwardedProps: input.forwardedProps,
    resume: asArray(input.resume).map(normalizeItemMetadata),
  };
};

const fromWireRunAgentInput = (value: unknown): LooseRecord | undefined => {
  const rec = asRecord(value);
  if (!rec) return undefined;
  const output: LooseRecord = {};
  if (rec.threadId !== undefined) output.threadId = rec.threadId;
  if (rec.runId !== undefined) output.runId = rec.runId;
  if (rec.protocolVersion !== undefined) output.protocolVersion = rec.protocolVersion;
  if (rec.parentRunId !== undefined) output.parentRunId = rec.parentRunId;
  if (rec.state !== undefined) output.state = rec.state;
  output.messages = asArray(rec.messages)
    .map(fromWireMessage)
    .filter((message) => message !== undefined);
  output.tools = asArray(rec.tools);
  output.context = asArray(rec.context);
  if (rec.forwardedProps !== undefined) output.forwardedProps = rec.forwardedProps;
  output.resume = asArray(rec.resume);
  return output;
};

/**
 * Encodes an event to the protobuf wire format.
 */
export function encode(event: BaseEvent): Uint8Array {
  event = omitOptionalNulls(event, "Event");
  // Events the handwritten SDK knows are validated, with a warning and a
  // best-effort fallback for malformed ones — existing clients encoding
  // invalid events keep working, loudly. Events the SDK does not know yet
  // (the schema can be ahead of it) are carried structurally.
  let validatedEvent: AGUIEvent | BaseEvent = event;
  if (KNOWN_TO_CORE.has(event.type as string)) {
    try {
      validatedEvent = EventSchemas.parse(event) as AGUIEvent;
    } catch (err) {
      // The paths the schema objected to, and nothing else. The event itself
      // used to ride along as a second console argument: on a stream that is a
      // wall of text around the one line that matters, and it prints whatever
      // the event was carrying — message content, raw provider payloads — into
      // logs that may have no business holding it. The paths say what to fix.
      //
      // Encoding continues regardless: the tolerance is the contract here, and
      // this only changes what the tolerance says on its way past.
      console.warn(
        `[ag-ui][proto.encode] Encoding ${String(event.type)} without validation: the schema rejected it at ${issuePaths(err)}. Encoded as given.`,
      );
      validatedEvent = event;
    }
  }
  const oneofField = toCamelCase(validatedEvent.type as string);
  const { type, timestamp, rawEvent, metadata, ...rest } = validatedEvent as unknown as LooseRecord;

  if (type === "MESSAGES_SNAPSHOT" && Array.isArray(rest.messages)) {
    rest.messages = rest.messages.map((message: unknown, index: number) =>
      toWireMessage(message, `messages[${index}]`),
    );
  }
  if (type === "RUN_FINISHED") {
    const outcomeRecord = asRecord(rest.outcome);
    rest.pendingToolCallIds = [];
    rest.interrupts = [];
    if (rest.outcome === undefined) {
      rest.outcome = "";
    } else if (outcomeRecord?.type === "success") {
      rest.outcome = "success";
      rest.pendingToolCallIds = asArray(outcomeRecord?.pendingToolCallIds);
    } else if (outcomeRecord?.type === "interrupt") {
      rest.outcome = "interrupt";
      rest.interrupts = asArray(outcomeRecord?.interrupts);
    } else if (outcomeRecord?.type === "cancelled") {
      rest.outcome = "cancelled";
    } else {
      rest.outcome = typeof outcomeRecord?.type === "string" ? outcomeRecord.type : "";
    }
  }
  if (type === "SUBAGENT_FINISHED") {
    const outcomeRecord = asRecord(rest.outcome);
    rest.interruptIds = [];
    if (rest.outcome === undefined) {
      rest.outcome = "";
    } else if (outcomeRecord?.type === "success") {
      rest.outcome = "success";
    } else if (outcomeRecord?.type === "suspended") {
      rest.outcome = "suspended";
      rest.interruptIds = asArray(outcomeRecord?.interruptIds);
    } else {
      rest.outcome = typeof outcomeRecord?.type === "string" ? outcomeRecord.type : "";
    }
  }
  if (type === "STATE_DELTA" && Array.isArray(rest.delta)) {
    rest.delta = (rest.delta as LooseRecord[]).map((operation) => ({
      ...operation,
      // Cast, not coercion: String(op) would turn malformed values such as
      // ["add"] into a valid enum member, where this throws instead.
      op: protoPatch.JsonPatchOperationType[
        (operation.op as string).toUpperCase() as keyof typeof protoPatch.JsonPatchOperationType
      ],
    }));
  }
  if (type === "ACTIVITY_DELTA" && Array.isArray(rest.patch)) {
    rest.patch = (rest.patch as LooseRecord[]).map((operation) => ({
      ...operation,
      // Cast, not coercion: String(op) would turn malformed values such as
      // ["add"] into a valid enum member, where this throws instead.
      op: protoPatch.JsonPatchOperationType[
        (operation.op as string).toUpperCase() as keyof typeof protoPatch.JsonPatchOperationType
      ],
    }));
  }
  if (type === "RUN_FINISHED") {
    rest.usage = asArray(rest.usage);
  }
  if (type === "RUN_ERROR") {
    rest.usage = asArray(rest.usage);
  }
  if (type === "TOOL_CALL_RESULT") {
    // content is a string or a parts array: a string keeps the field,
    // parts take contentParts — the same split as on the merged Message.
    if (Array.isArray(rest.content)) {
      rest.contentParts = rest.content
        .map((part: unknown, index: number) => {
          const mapped = toProtoContentPart(part);
          if (mapped === undefined) {
            warnUnencodableContentPart("TOOL_CALL_RESULT.content", index);
          }
          return mapped;
        })
        .filter((part: unknown) => part !== undefined);
      rest.content = undefined;
    } else {
      rest.contentParts = [];
    }
  }
  if (type === "RUN_STARTED" && rest.input !== undefined) {
    rest.input = toWireRunAgentInput(rest.input);
  }

  const eventMessage = {
    [oneofField]: {
      baseEvent: {
        type: protoEvents.EventType[event.type as keyof typeof protoEvents.EventType],
        timestamp,
        rawEvent,
        metadata: normalizeMetadata(metadata),
      },
      ...rest,
    },
  };
  return protoEvents.Event.encode(eventMessage).finish();
}

/**
 * Decodes the protobuf wire format to an event.
 */
/**
 * One message level: singular fields merge, descents guide both the guard
 * and merger, and oneof arms are mutually exclusive within an occurrence.
 * Google payloads are traversed only by the merger, not by the wire guard.
 */
interface ScanSpec {
  singular: Set<number>;
  descend: Record<number, string | undefined>;
  google?: Record<number, string | undefined>;
  arms?: Set<number>;
  armWireTypes?: Record<number, number>;
}

const SCAN_SPECS: Record<string, ScanSpec | undefined> = {
  TextMessageStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  BaseEvent: {
    singular: new Set([3, 4]),
    descend: {},
    google: { 3: "google.protobuf.Value", 4: "google.protobuf.Struct" },
  },
  TextMessageContentEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  TextMessageEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallArgsEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StateSnapshotEvent: {
    singular: new Set([1, 2]),
    descend: { 1: "BaseEvent" },
    google: { 2: "google.protobuf.Value" },
  },
  StateDeltaEvent: { singular: new Set([1]), descend: { 1: "BaseEvent", 2: "JsonPatchOperation" } },
  JsonPatchOperation: {
    singular: new Set([4]),
    descend: {},
    google: { 4: "google.protobuf.Value" },
  },
  MessagesSnapshotEvent: { singular: new Set([1]), descend: { 1: "BaseEvent", 2: "Message" } },
  Message: {
    singular: new Set([9, 13]),
    descend: { 5: "ToolCall", 8: "InputContent" },
    google: { 9: "google.protobuf.Struct", 13: "google.protobuf.Struct" },
  },
  ToolCall: { singular: new Set([3, 4]), descend: {}, google: { 4: "google.protobuf.Struct" } },
  InputContent: {
    singular: new Set([1, 2, 3, 4, 5]),
    descend: {
      1: "TextInputPart",
      2: "ImageInputPart",
      3: "AudioInputPart",
      4: "VideoInputPart",
      5: "DocumentInputPart",
    },
    arms: new Set([1, 2, 3, 4, 5]),
  },
  TextInputPart: { singular: new Set([3]), descend: {}, google: { 3: "google.protobuf.Value" } },
  ImageInputPart: {
    singular: new Set([1, 2]),
    descend: { 1: "InputContentSource" },
    google: { 2: "google.protobuf.Value" },
  },
  InputContentSource: { singular: new Set([1, 2, 3]), descend: {}, arms: new Set([1, 2, 3]) },
  AudioInputPart: {
    singular: new Set([1, 2]),
    descend: { 1: "InputContentSource" },
    google: { 2: "google.protobuf.Value" },
  },
  VideoInputPart: {
    singular: new Set([1, 2]),
    descend: { 1: "InputContentSource" },
    google: { 2: "google.protobuf.Value" },
  },
  DocumentInputPart: {
    singular: new Set([1, 2]),
    descend: { 1: "InputContentSource" },
    google: { 2: "google.protobuf.Value" },
  },
  RawEvent: {
    singular: new Set([1, 2]),
    descend: { 1: "BaseEvent" },
    google: { 2: "google.protobuf.Value" },
  },
  CustomEvent: {
    singular: new Set([1, 3]),
    descend: { 1: "BaseEvent" },
    google: { 3: "google.protobuf.Value" },
  },
  RunStartedEvent: { singular: new Set([1, 5]), descend: { 1: "BaseEvent", 5: "RunAgentInput" } },
  RunAgentInput: {
    singular: new Set([4, 8]),
    descend: { 5: "Message", 6: "Tool", 9: "ResumeEntry" },
    google: { 4: "google.protobuf.Value", 8: "google.protobuf.Value" },
  },
  Tool: {
    singular: new Set([3, 4]),
    descend: {},
    google: { 3: "google.protobuf.Value", 4: "google.protobuf.Struct" },
  },
  ResumeEntry: {
    singular: new Set([3, 4]),
    descend: {},
    google: { 3: "google.protobuf.Value", 4: "google.protobuf.Struct" },
  },
  RunFinishedEvent: {
    singular: new Set([1, 4]),
    descend: { 1: "BaseEvent", 6: "Interrupt" },
    google: { 4: "google.protobuf.Value" },
  },
  Interrupt: {
    singular: new Set([5, 7]),
    descend: {},
    google: { 5: "google.protobuf.Value", 7: "google.protobuf.Value" },
  },
  RunErrorEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StepStartedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StepFinishedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  TextMessageChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  SubagentStartedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  SubagentFinishedEvent: {
    singular: new Set([1, 3]),
    descend: { 1: "BaseEvent" },
    google: { 3: "google.protobuf.Value" },
  },
  SubagentErrorEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallResultEvent: { singular: new Set([1]), descend: { 1: "BaseEvent", 7: "InputContent" } },
  ActivitySnapshotEvent: {
    singular: new Set([1, 5]),
    descend: { 1: "BaseEvent" },
    google: { 5: "google.protobuf.Struct" },
  },
  ActivityDeltaEvent: {
    singular: new Set([1]),
    descend: { 1: "BaseEvent", 5: "JsonPatchOperation" },
  },
  ReasoningStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageContentEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningEncryptedValueEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  // Standard google/protobuf/struct.proto wire definitions. Map entries and
  // list elements are repeated; Value's active kind follows protobuf oneof rules.
  "google.protobuf.Struct": {
    singular: new Set(),
    descend: { 1: "google.protobuf.Struct.FieldsEntry" },
  },
  "google.protobuf.Struct.FieldsEntry": {
    singular: new Set([2]),
    descend: { 2: "google.protobuf.Value" },
  },
  "google.protobuf.Value": {
    singular: new Set([5, 6]),
    descend: { 5: "google.protobuf.Struct", 6: "google.protobuf.ListValue" },
    arms: new Set([1, 2, 3, 4, 5, 6]),
    armWireTypes: { 1: 0, 2: 1, 3: 2, 4: 0, 5: 2, 6: 2 },
  },
  "google.protobuf.ListValue": {
    singular: new Set(),
    descend: { 1: "google.protobuf.Value" },
  },
};

/** Envelope entry number -> event message name, all descended into. */
const ENVELOPE_SCAN: Record<number, string | undefined> = {
  1: "TextMessageStartEvent",
  2: "TextMessageContentEvent",
  3: "TextMessageEndEvent",
  4: "ToolCallStartEvent",
  5: "ToolCallArgsEvent",
  6: "ToolCallEndEvent",
  7: "StateSnapshotEvent",
  8: "StateDeltaEvent",
  9: "MessagesSnapshotEvent",
  10: "RawEvent",
  11: "CustomEvent",
  12: "RunStartedEvent",
  13: "RunFinishedEvent",
  14: "RunErrorEvent",
  15: "StepStartedEvent",
  16: "StepFinishedEvent",
  17: "TextMessageChunkEvent",
  18: "ToolCallChunkEvent",
  19: "SubagentStartedEvent",
  20: "SubagentFinishedEvent",
  21: "SubagentErrorEvent",
  22: "ToolCallResultEvent",
  23: "ActivitySnapshotEvent",
  24: "ActivityDeltaEvent",
  25: "ReasoningStartEvent",
  26: "ReasoningMessageStartEvent",
  27: "ReasoningMessageContentEvent",
  28: "ReasoningMessageEndEvent",
  29: "ReasoningMessageChunkEvent",
  30: "ReasoningEndEvent",
  31: "ReasoningEncryptedValueEvent",
};

// Mirrors the wire reader's uint32 truncation exactly: the fifth byte
// contributes only its low four bits, later bytes none — otherwise an
// overlong encoding of a tag would dodge duplicate detection while the
// real decoder still reads the canonical field number.
function readVarint(data: Uint8Array, cursor: { offset: number }): number {
  let result = 0;
  let shift = 0;
  for (;;) {
    if (cursor.offset >= data.length) throw new Error("Invalid event");
    const byte = data[cursor.offset++];
    if (shift < 28) result += (byte & 0x7f) * 2 ** shift;
    else if (shift === 28) result += (byte & 0x0f) * 2 ** 28;
    shift += 7;
    if ((byte & 0x80) === 0) return result;
  }
}

/** Walks one message level of the scan graph, recursing along descend edges. */
function scanMessage(data: Uint8Array, spec: ScanSpec): void {
  const cursor = { offset: 0 };
  let groupDepth = 0;
  let seenArm = 0;
  while (cursor.offset < data.length) {
    const tag = readVarint(data, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    if (field === 0) {
      throw new Error("Invalid event");
    }
    if (wireType === 3) {
      groupDepth += 1;
      continue;
    }
    if (wireType === 4) {
      groupDepth -= 1;
      if (groupDepth < 0) throw new Error("Invalid event");
      continue;
    }
    if (wireType === 0) {
      readVarint(data, cursor);
    } else if (wireType === 1) {
      cursor.offset += 8;
    } else if (wireType === 2) {
      const length = readVarint(data, cursor);
      if (cursor.offset + length > data.length) throw new Error("Invalid event");
      if (groupDepth === 0) {
        if (spec.arms?.has(field)) {
          if (seenArm !== 0 && seenArm !== field) throw new Error("Invalid event");
          seenArm = field;
        }
        const child = spec.descend[field];
        if (child !== undefined) {
          const childSpec = SCAN_SPECS[child];
          if (childSpec !== undefined) {
            scanMessage(data.subarray(cursor.offset, cursor.offset + length), childSpec);
          }
        }
      }
      cursor.offset += length;
    } else if (wireType === 5) {
      cursor.offset += 4;
    } else {
      throw new Error("Invalid event");
    }
    if (cursor.offset > data.length) throw new Error("Invalid event");
  }
  if (groupDepth !== 0) throw new Error("Invalid event");
}

/**
 * Rejects an envelope naming different known event kinds, then checks each
 * payload. Repeated occurrences of the same kind merge during decoding.
 * Unknown fields are protobuf's to ignore, repeated or not.
 */
function assertWellFormedEnvelope(data: Uint8Array): void {
  const seen = new Set<number>();
  const cursor = { offset: 0 };
  // Legacy group wire types nest; everything inside a group is an unknown
  // field a protobuf decoder skips, so the scan skips it too.
  let groupDepth = 0;
  while (cursor.offset < data.length) {
    const tag = readVarint(data, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    // Field zero is not a legal tag: canonical decoders reject it while
    // ts-proto silently stops reading, which would truncate the stream in
    // one runtime and error in another.
    if (field === 0) {
      throw new Error("Invalid event");
    }
    if (wireType === 3) {
      groupDepth += 1;
      continue;
    }
    if (wireType === 4) {
      groupDepth -= 1;
      if (groupDepth < 0) throw new Error("Invalid event");
      continue;
    }
    if (groupDepth === 0 && ENVELOPE_TAGS.has(field)) {
      if (seen.size > 0 && !seen.has(field)) {
        throw new Error("Invalid event");
      }
      seen.add(field);
    }
    if (wireType === 0) {
      readVarint(data, cursor);
    } else if (wireType === 1) {
      cursor.offset += 8;
    } else if (wireType === 2) {
      const length = readVarint(data, cursor);
      if (cursor.offset + length > data.length) throw new Error("Invalid event");
      if (groupDepth === 0) {
        const child = ENVELOPE_SCAN[field];
        if (child !== undefined) {
          const childSpec = SCAN_SPECS[child];
          if (childSpec !== undefined) {
            scanMessage(data.subarray(cursor.offset, cursor.offset + length), childSpec);
          }
        }
      }
      cursor.offset += length;
    } else if (wireType === 5) {
      cursor.offset += 4;
    } else {
      throw new Error("Invalid event");
    }
    if (cursor.offset > data.length) throw new Error("Invalid event");
  }
  if (groupDepth !== 0) throw new Error("Invalid event");
}

function concatenate(parts: Uint8Array[]): Uint8Array {
  if (parts.length === 1) return parts[0];
  const result = new Uint8Array(parts.reduce((length, part) => length + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}

/**
 * ts-proto replaces singular messages instead of merging them. Combine their
 * wire payloads before decoding so explicit scalar defaults, repeated arrays,
 * maps and nested message presence survive. Already canonical bytes are reused.
 */
function mergeMessageFields(data: Uint8Array, spec: ScanSpec): Uint8Array {
  const reader = new BinaryReader(data);
  const fields: Array<
    | {
        number: number;
        raw: Uint8Array;
        payloads?: Uint8Array[];
        child?: ScanSpec;
      }
    | undefined
  > = [];
  const positions = new Map<number, number>();
  let activeArm: number | undefined;
  let changed = false;
  while (reader.pos < reader.len) {
    const start = reader.pos;
    const [number, wireType] = reader.tag();
    const payload = wireType === 2 ? reader.bytes() : undefined;
    if (payload === undefined) reader.skip(wireType, number);
    const isArm = spec.arms?.has(number) && wireType === (spec.armWireTypes?.[number] ?? 2);
    if (isArm) {
      if (activeArm !== undefined && activeArm !== number) {
        const previous = positions.get(activeArm);
        if (previous !== undefined) fields[previous] = undefined;
        positions.delete(activeArm);
        changed = true;
      }
      activeArm = number;
      if (!spec.singular.has(number)) {
        const previous = positions.get(number);
        if (previous !== undefined) {
          fields[previous] = undefined;
          positions.delete(number);
          changed = true;
        }
      }
    }
    const childName = spec.descend[number] ?? spec.google?.[number];
    const isMessage =
      payload !== undefined && (spec.singular.has(number) || childName !== undefined);
    const previous = positions.get(number);
    const previousPayloads = previous === undefined ? undefined : fields[previous]?.payloads;
    if (isMessage && spec.singular.has(number) && previousPayloads !== undefined) {
      previousPayloads.push(payload);
      changed = true;
      continue;
    }
    if (isMessage || isArm) positions.set(number, fields.length);
    fields.push({
      number,
      raw: data.subarray(start, reader.pos),
      ...(isMessage && { payloads: [payload] }),
      child: childName === undefined ? undefined : SCAN_SPECS[childName],
    });
  }
  const parts: Uint8Array[] = [];
  for (const field of fields) {
    if (field === undefined) continue;
    if (field.payloads !== undefined) {
      const combined = concatenate(field.payloads);
      const merged =
        field.child === undefined ? combined : mergeMessageFields(combined, field.child);
      if (field.payloads.length > 1 || merged !== combined) {
        parts.push(
          new BinaryWriter()
            .uint32(field.number * 8 + 2)
            .bytes(merged)
            .finish(),
        );
        changed = true;
        continue;
      }
    }
    parts.push(field.raw);
  }
  return changed ? concatenate(parts) : data;
}

/**
 * The envelope carried nothing but variants this build was not compiled
 * against — an event from a later protocol, rather than broken bytes.
 *
 * Kept distinct from a decode failure on purpose. An SSE reader hands such an
 * event to the pipeline, which drops it with a warning and carries on; the
 * binary reader cannot hand it over at all, because an unknown arm has no type
 * string to put on it. Naming the case lets the caller drop the frame the same
 * way, so a producer that adds an event does not kill every binary client
 * while text clients sail past it.
 */
export class AGUIUnknownEventTypeError extends Error {
  constructor(message = "Unknown event type") {
    super(message);
    this.name = "AGUIUnknownEventTypeError";
  }
}

/**
 * Reads a varint that must fit the width its position allows, returning -1 for
 * anything unreadable or too wide.
 *
 * readVarint above deliberately MASKS the overflow bits instead, mirroring the
 * wire reader so that an overlong tag cannot dodge duplicate detection. The
 * walkers below want the opposite: masking would quietly turn a field number
 * or a length that no protobuf encoder can produce into a smaller, plausible
 * one, and broken bytes would read as a well-formed message.
 *
 * The line these walkers hold is well-formed PROTOBUF, never conformance to a
 * schema. A tag or a length that overflows its width is not protobuf at all; a
 * field number protobuf reserves by convention still is, and judging that would
 * be judging the shape of an arm this build was never compiled against.
 */
function boundedVarint(
  data: Uint8Array,
  cursor: { offset: number },
  maxBytes: number,
  lastByteMax: number,
): number {
  let result = 0;
  let shift = 0;
  let bytes = 0;
  for (;;) {
    if (cursor.offset >= data.length || bytes >= maxBytes) return -1;
    const byte = data[cursor.offset++];
    bytes += 1;
    // The final byte carries only the bits the width has left over, so a bigger
    // one encodes a number the field could never hold. A continuation bit here
    // fails the same test, since it asks for a byte the width does not have.
    if (bytes === maxBytes && byte > lastByteMax) return -1;
    result += (byte & 0x7f) * 2 ** shift;
    shift += 7;
    if ((byte & 0x80) === 0) return result;
  }
}

/**
 * A tag and a length are both uint32 on the wire: five bytes, the last holding
 * four bits. Capping a tag there caps the field number at protobuf's own
 * maximum, since the tag is the field number shifted left by three.
 */
const varint32 = (data: Uint8Array, cursor: { offset: number }): number =>
  boundedVarint(data, cursor, 5, 0x0f);

/** A varint-typed VALUE is uint64: ten bytes, the last holding one bit. */
const varint64 = (data: Uint8Array, cursor: { offset: number }): number =>
  boundedVarint(data, cursor, 10, 0x01);

/**
 * Whether the given bytes walk cleanly as a protobuf message.
 *
 * Used on the payload of an arm this build does not know, where nothing else
 * can vouch for it: the generated parser skips an unknown field without ever
 * reading inside it, so bytes that encode no message at all would otherwise be
 * indistinguishable from an event from the future.
 *
 * Deliberately a WELL-FORMEDNESS check and nothing more. It asks whether the
 * bytes are a protobuf message, never whether they are an AG-UI event — an arm
 * this build has not been compiled against may be shaped in ways this version
 * cannot anticipate, and demanding a familiar shape would reject exactly the
 * future events this whole path exists to survive. For the same reason it does
 * not recurse: at this level a length-delimited run of bytes is equally a
 * nested message, a string or a blob, so its insides settle nothing either way.
 */
function walksAsMessage(data: Uint8Array): boolean {
  const cursor = { offset: 0 };
  const groups: number[] = [];
  while (cursor.offset < data.length) {
    const tag = varint32(data, cursor);
    if (tag < 0) return false;
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    if (field === 0) return false;
    if (wireType === 3) {
      groups.push(field);
    } else if (wireType === 4) {
      // A legacy group closes with the field number it opened with; any other
      // pairing is a frame no encoder produces.
      if (groups.pop() !== field) return false;
    } else if (wireType === 0) {
      if (varint64(data, cursor) < 0) return false;
    } else if (wireType === 1) {
      cursor.offset += 8;
    } else if (wireType === 5) {
      cursor.offset += 4;
    } else if (wireType === 2) {
      const length = varint32(data, cursor);
      if (length < 0 || cursor.offset + length > data.length) return false;
      cursor.offset += length;
    } else {
      return false;
    }
    if (cursor.offset > data.length) return false;
  }
  return groups.length === 0;
}

/**
 * Whether the frame names one or more arms from a later protocol and nothing
 * this build could have read.
 *
 * Only consulted once the generated parser has found no known arm, because a
 * frame that DOES carry one is already answered: protobuf ignores unknown
 * fields, and this envelope is no exception — a later version may add fields
 * beside the arms, and rejecting a frame for carrying one would break every
 * older reader the moment it shipped. That rule is settled and tested.
 *
 * With no known arm the frame is either an event this build predates or broken
 * bytes, and the two must not share an answer. A known tag that failed to
 * parse, or any tag of a wire type no arm uses, means broken; at least one
 * unknown length-delimited field whose payload walks as a message means an
 * event from the future, which the caller drops the way enforcement drops an
 * unrecognised event off an SSE stream.
 */
function namesOnlyFutureArms(data: Uint8Array): boolean {
  const cursor = { offset: 0 };
  const groups: number[] = [];
  let future = 0;
  while (cursor.offset < data.length) {
    const tag = varint32(data, cursor);
    if (tag < 0) return false;
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    if (field === 0) return false;
    // Inside an unknown group every field is that group's business, so it is
    // skipped wholesale rather than read as a tag of the envelope.
    const atTopLevel = groups.length === 0;
    if (wireType === 3) {
      // Every arm of the envelope is a length-delimited message, so a known tag
      // opening a group names an event this build knows in a shape no encoder
      // writes. Checked before descending, because inside the group the tags
      // belong to the group rather than to the envelope.
      if (atTopLevel && ENVELOPE_TAGS.has(field)) return false;
      groups.push(field);
    } else if (wireType === 4) {
      if (groups.pop() !== field) return false;
    } else if (wireType === 0) {
      if (atTopLevel && ENVELOPE_TAGS.has(field)) return false;
      if (varint64(data, cursor) < 0) return false;
    } else if (wireType === 1) {
      if (atTopLevel && ENVELOPE_TAGS.has(field)) return false;
      cursor.offset += 8;
    } else if (wireType === 5) {
      if (atTopLevel && ENVELOPE_TAGS.has(field)) return false;
      cursor.offset += 4;
    } else if (wireType === 2) {
      const length = varint32(data, cursor);
      if (length < 0 || cursor.offset + length > data.length) return false;
      if (atTopLevel) {
        // A known arm the parser could not populate: the frame names an event
        // this build knows and failed to read it, which is broken input.
        if (ENVELOPE_TAGS.has(field)) return false;
        if (!walksAsMessage(data.subarray(cursor.offset, cursor.offset + length))) {
          return false;
        }
        future += 1;
      }
      cursor.offset += length;
    } else {
      return false;
    }
    if (cursor.offset > data.length) return false;
  }
  return groups.length === 0 && future > 0;
}

export function decode(data: Uint8Array): BaseEvent {
  assertWellFormedEnvelope(data);
  const envelope = protoEvents.Event.decode(
    mergeMessageFields(data, {
      singular: ENVELOPE_TAGS,
      descend: ENVELOPE_SCAN,
    }),
  );
  // Exactly one oneof entry. ts-proto's field-per-entry decoding cannot
  // reproduce protobuf's last-field-wins for a malformed envelope carrying
  // several, so the deterministic behaviour is to reject it loudly rather
  // than silently pick a different event than another runtime would.
  const populated = Object.entries(envelope).filter(([, value]) => value !== undefined);
  if (populated.length !== 1) {
    // No arm this build knows. If the frame names one from a later protocol
    // instead, the two transports must agree about it: over SSE such an event
    // reaches enforcement and is dropped with a warning, so over binary it must
    // not be fatal either. Anything else here is malformed and stays fatal — an
    // empty envelope names nothing, and bytes that encode no message are broken
    // rather than a message to learn about later.
    if (populated.length === 0 && namesOnlyFutureArms(data)) {
      throw new AGUIUnknownEventTypeError();
    }
    throw new Error("Invalid event");
  }
  const entry = populated[0];
  // The oneof entry selected the message shape, so it names the type; a
  // base_event.type that disagrees is a malformed event, not a tiebreak.
  const entryType = ENVELOPE_TYPE[entry[0]];
  if (entryType === undefined) {
    throw new Error("Invalid event");
  }
  const decoded = entry[1] as LooseRecord;
  const base = asRecord(decoded.baseEvent);
  if (!base) {
    throw new Error("Invalid event");
  }
  const declaredType = protoEvents.EventType[base.type as number];
  if (declaredType !== entryType) {
    throw new Error(
      "Invalid event: envelope carries " +
        entryType +
        " but the base event declares " +
        String(declaredType),
    );
  }
  decoded.type = entryType;
  decoded.timestamp = base.timestamp;
  decoded.rawEvent = base.rawEvent;
  // Struct decodes an absent object to undefined, so an event that carried no
  // metadata stays without the key rather than gaining an empty one.
  if (base.metadata !== undefined) {
    decoded.metadata = base.metadata;
  }
  delete decoded.baseEvent;

  if (decoded.type === "MESSAGES_SNAPSHOT" && Array.isArray(decoded.messages)) {
    decoded.messages = (decoded.messages as unknown[])
      .map(fromWireMessage)
      .filter((message) => message !== undefined);
  }
  if (decoded.type === "RUN_FINISHED") {
    const record = decoded as LooseRecord;
    const wireOutcome =
      typeof record.outcome === "string" && record.outcome !== ""
        ? (record.outcome as string)
        : undefined;
    const payload: LooseRecord = {};
    payload.pendingToolCallIds = record.pendingToolCallIds;
    delete record.pendingToolCallIds;
    payload.interrupts = record.interrupts;
    delete record.interrupts;
    delete record.outcome;
    if (wireOutcome === undefined) {
      if (asArray(payload.pendingToolCallIds).length > 0) {
        record.pendingToolCallIds = payload.pendingToolCallIds;
      }
      if (asArray(payload.interrupts).length > 0) {
        record.interrupts = payload.interrupts;
      }
    }
    if (wireOutcome === "success") {
      record.outcome = {
        type: "success",
        ...(asArray(payload.pendingToolCallIds).length > 0
          ? { pendingToolCallIds: payload.pendingToolCallIds }
          : {}),
        ...(asArray(payload.interrupts).length > 0 ? { interrupts: payload.interrupts } : {}),
      };
    }
    if (wireOutcome === "interrupt") {
      record.outcome = {
        type: "interrupt",
        interrupts: asArray(payload.interrupts),
        ...(asArray(payload.pendingToolCallIds).length > 0
          ? { pendingToolCallIds: payload.pendingToolCallIds }
          : {}),
      };
    }
    if (wireOutcome === "cancelled") {
      record.outcome = {
        type: "cancelled",
        ...(asArray(payload.pendingToolCallIds).length > 0
          ? { pendingToolCallIds: payload.pendingToolCallIds }
          : {}),
        ...(asArray(payload.interrupts).length > 0 ? { interrupts: payload.interrupts } : {}),
      };
    }
    // An unrecognised outcome is still representable as JSON, so it
    // is rebuilt as it was sent rather than judged here. Decoding bytes into
    // events is transport work; deciding what an unrecognised value MEANS
    // belongs to the one enforcement stage every transport shares, so that a
    // stream cannot survive over SSE and fail over binary. Which payload an
    // unknown case owns is unknowable, so whatever arrived rides along for
    // enforcement to strip with the rest.
    if (wireOutcome !== undefined && !["success", "interrupt", "cancelled"].includes(wireOutcome)) {
      record.outcome = {
        type: wireOutcome,
        ...(asArray(payload.pendingToolCallIds).length > 0
          ? { pendingToolCallIds: payload.pendingToolCallIds }
          : {}),
        ...(asArray(payload.interrupts).length > 0 ? { interrupts: payload.interrupts } : {}),
      };
    }
  }
  if (decoded.type === "SUBAGENT_FINISHED") {
    const record = decoded as LooseRecord;
    const wireOutcome =
      typeof record.outcome === "string" && record.outcome !== ""
        ? (record.outcome as string)
        : undefined;
    const payload: LooseRecord = {};
    payload.interruptIds = record.interruptIds;
    delete record.interruptIds;
    delete record.outcome;
    if (wireOutcome === undefined) {
      if (asArray(payload.interruptIds).length > 0) {
        record.interruptIds = payload.interruptIds;
      }
    }
    if (wireOutcome === "success") {
      record.outcome = {
        type: "success",
        ...(asArray(payload.interruptIds).length > 0 ? { interruptIds: payload.interruptIds } : {}),
      };
    }
    if (wireOutcome === "suspended") {
      record.outcome = {
        type: "suspended",
        ...(asArray(payload.interruptIds).length > 0 ? { interruptIds: payload.interruptIds } : {}),
      };
    }
    // An unrecognised outcome is still representable as JSON, so it
    // is rebuilt as it was sent rather than judged here. Decoding bytes into
    // events is transport work; deciding what an unrecognised value MEANS
    // belongs to the one enforcement stage every transport shares, so that a
    // stream cannot survive over SSE and fail over binary. Which payload an
    // unknown case owns is unknowable, so whatever arrived rides along for
    // enforcement to strip with the rest.
    if (wireOutcome !== undefined && !["success", "suspended"].includes(wireOutcome)) {
      record.outcome = {
        type: wireOutcome,
        ...(asArray(payload.interruptIds).length > 0 ? { interruptIds: payload.interruptIds } : {}),
      };
    }
  }
  if (decoded.type === "STATE_DELTA" && Array.isArray(decoded.delta)) {
    // An operation this build cannot name is never invented and never fatal —
    // and never dropped here either. An operation added to JSON Patch after
    // this build shipped arrives over SSE as an unrecognised union member,
    // which enforcement removes from the array and NAMES; throwing here made
    // the same patch fatal over binary and survivable over SSE, and filtering
    // it out here made it vanish over binary with nothing said, while the same
    // patch over SSE printed the path it lost.
    //
    // The enum value is all the wire carries for an operation this build has no
    // name for, so it rides on as its own decimal spelling. That is not a valid
    // JSON Patch op either — which is the point: enforcement reads it as the
    // unrecognised union member it is, strips the operation and says so.
    decoded.delta = (decoded.delta as LooseRecord[]).map((operation) => {
      const opName =
        protoPatch.JsonPatchOperationType[operation.op as protoPatch.JsonPatchOperationType];
      operation.op =
        typeof opName === "string" && opName !== "UNRECOGNIZED"
          ? opName.toLowerCase()
          : String(operation.op);
      Object.keys(operation).forEach((key) => {
        if (operation[key] === undefined) {
          delete operation[key];
        }
      });
      return operation;
    });
  }
  if (decoded.type === "ACTIVITY_DELTA" && Array.isArray(decoded.patch)) {
    // An operation this build cannot name is never invented and never fatal —
    // and never dropped here either. An operation added to JSON Patch after
    // this build shipped arrives over SSE as an unrecognised union member,
    // which enforcement removes from the array and NAMES; throwing here made
    // the same patch fatal over binary and survivable over SSE, and filtering
    // it out here made it vanish over binary with nothing said, while the same
    // patch over SSE printed the path it lost.
    //
    // The enum value is all the wire carries for an operation this build has no
    // name for, so it rides on as its own decimal spelling. That is not a valid
    // JSON Patch op either — which is the point: enforcement reads it as the
    // unrecognised union member it is, strips the operation and says so.
    decoded.patch = (decoded.patch as LooseRecord[]).map((operation) => {
      const opName =
        protoPatch.JsonPatchOperationType[operation.op as protoPatch.JsonPatchOperationType];
      operation.op =
        typeof opName === "string" && opName !== "UNRECOGNIZED"
          ? opName.toLowerCase()
          : String(operation.op);
      Object.keys(operation).forEach((key) => {
        if (operation[key] === undefined) {
          delete operation[key];
        }
      });
      return operation;
    });
  }
  if (decoded.type === "RUN_FINISHED") {
    if (Array.isArray(decoded.usage) && decoded.usage.length === 0) {
      delete decoded.usage;
    }
  }
  if (decoded.type === "RUN_ERROR") {
    if (Array.isArray(decoded.usage) && decoded.usage.length === 0) {
      delete decoded.usage;
    }
  }
  if (decoded.type === "TOOL_CALL_RESULT") {
    const record = decoded as LooseRecord;
    if (record.content !== undefined && asArray(record.contentParts).length > 0) {
      // String content and parts together is a contradiction the encoder never
      // writes; resolving it either way would silently discard the other half.
      throw new Error("Invalid event: content carries both string content and content parts");
    }
    if (record.content === undefined) {
      // String content rides the field; anything else is the parts array —
      // including an empty one, which is valid content of its own. A part
      // naming no arm this build knows is dropped with a warning, as on the
      // merged Message and for the same reason: the JSON path strips an
      // unrecognised union member rather than failing the event.
      record.content = asArray(record.contentParts)
        .map((part: unknown) => {
          const mapped = fromProtoContentPart(part);
          if (mapped === undefined) warnDroppedContentPart();
          return mapped;
        })
        .filter((part: unknown) => part !== undefined);
    }
    delete record.contentParts;
  }
  if (decoded.type === "RUN_STARTED" && decoded.input !== undefined) {
    decoded.input = fromWireRunAgentInput(decoded.input);
  }

  dropUndefinedDeep(decoded);

  // Deliberately unvalidated. Decoding turns bytes into the event a producer
  // sent, which is the same job the SSE reader does with JSON.parse and no
  // more; the client pipeline then strips, enforces and verifies whatever
  // arrives, identically for both transports. Validating here as well made the
  // binary path strictly harsher than the text one — an event carrying
  // anything this build did not recognise threw at the transport instead of
  // reaching enforcement, so the same stream succeeded over SSE and failed
  // over protobuf. The structural guards above stay: bytes that map to no
  // valid event at all are a decode failure, and that IS transport work.
  return decoded as unknown as BaseEvent;
}
