import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Declare Dojo SSE as UTF-8 and canonicalize contractual traces
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"steps": [{"description": "Crack eggs into bowl", "status": "enabled"}, {"description": "Preheat oven to 350F", "status": "enabled"}, {"description": "Mix and bake for 25 min", "status": "enabled"}]}' as const;
const shared2 =
  '{"steps": [{"description": "Start The Planning", "status": "enabled"}, {"description": "Design spacecraft", "status": "enabled"}, {"description": "Launch mission", "status": "enabled"}]}' as const;
const shared3 =
  "Give me a plan to make brownies, there should be only one step with eggs and one step with oven, this is a strict requirement so adhere" as const;
const shared4 =
  "Does the planner include Start The Planning? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared5 =
  "Does the planner include eggs? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared6 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Crack eggs into bowl",
                status: "enabled",
              },
              {
                description: "Preheat oven to 350F",
                status: "enabled",
              },
              {
                description: "Mix and bake for 25 min",
                status: "enabled",
              },
            ],
          },
          id: "id-7",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-9",
      tool_call_id: "id-7",
      artifact: null,
      status: "success",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-10",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  steps: [
    {
      description: "Crack eggs into bowl",
      status: "enabled",
    },
    {
      description: "Preheat oven to 350F",
      status: "enabled",
    },
    {
      description: "Mix and bake for 25 min",
      status: "enabled",
    },
  ],
  tools: [
    {
      name: "generate_task_steps",
      description: "Generates a list of steps for the user to perform",
      parameters: {
        type: "object",
        properties: {
          steps: {
            type: "array",
            items: {
              type: "object",
              properties: {
                description: {
                  type: "string",
                },
                status: {
                  type: "string",
                  enum: ["enabled", "disabled", "executing"],
                },
              },
              required: ["description", "status"],
            },
          },
        },
        required: ["steps"],
      },
    },
  ],
} as const;
const shared7 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content:
        "Plan a mission to Mars with the first step being Start The Planning",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Start The Planning",
                status: "enabled",
              },
              {
                description: "Design spacecraft",
                status: "enabled",
              },
              {
                description: "Launch mission",
                status: "enabled",
              },
            ],
          },
          id: "id-7",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-9",
      tool_call_id: "id-7",
      artifact: null,
      status: "success",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-10",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  steps: [
    {
      description: "Start The Planning",
      status: "enabled",
    },
    {
      description: "Design spacecraft",
      status: "enabled",
    },
    {
      description: "Launch mission",
      status: "enabled",
    },
  ],
  tools: [
    {
      name: "generate_task_steps",
      description: "Generates a list of steps for the user to perform",
      parameters: {
        type: "object",
        properties: {
          steps: {
            type: "array",
            items: {
              type: "object",
              properties: {
                description: {
                  type: "string",
                },
                status: {
                  type: "string",
                  enum: ["enabled", "disabled", "executing"],
                },
              },
              required: ["description", "status"],
            },
          },
        },
        required: ["steps"],
      },
    },
  ],
} as const;
const shared8 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Crack eggs into bowl",
                status: "enabled",
              },
              {
                description: "Preheat oven to 350F",
                status: "enabled",
              },
              {
                description: "Mix and bake for 25 min",
                status: "enabled",
              },
            ],
          },
          id: "id-7",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-9",
      tool_call_id: "id-7",
      artifact: null,
      status: "success",
    },
  ],
  steps: [
    {
      description: "Crack eggs into bowl",
      status: "enabled",
    },
    {
      description: "Preheat oven to 350F",
      status: "enabled",
    },
    {
      description: "Mix and bake for 25 min",
      status: "enabled",
    },
  ],
  tools: [
    {
      name: "generate_task_steps",
      description: "Generates a list of steps for the user to perform",
      parameters: {
        type: "object",
        properties: {
          steps: {
            type: "array",
            items: {
              type: "object",
              properties: {
                description: {
                  type: "string",
                },
                status: {
                  type: "string",
                  enum: ["enabled", "disabled", "executing"],
                },
              },
              required: ["description", "status"],
            },
          },
        },
        required: ["steps"],
      },
    },
  ],
} as const;
const shared9 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content:
        "Plan a mission to Mars with the first step being Start The Planning",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Start The Planning",
                status: "enabled",
              },
              {
                description: "Design spacecraft",
                status: "enabled",
              },
              {
                description: "Launch mission",
                status: "enabled",
              },
            ],
          },
          id: "id-7",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-9",
      tool_call_id: "id-7",
      artifact: null,
      status: "success",
    },
  ],
  steps: [
    {
      description: "Start The Planning",
      status: "enabled",
    },
    {
      description: "Design spacecraft",
      status: "enabled",
    },
    {
      description: "Launch mission",
      status: "enabled",
    },
  ],
  tools: [
    {
      name: "generate_task_steps",
      description: "Generates a list of steps for the user to perform",
      parameters: {
        type: "object",
        properties: {
          steps: {
            type: "array",
            items: {
              type: "object",
              properties: {
                description: {
                  type: "string",
                },
                status: {
                  type: "string",
                  enum: ["enabled", "disabled", "executing"],
                },
              },
              required: ["description", "status"],
            },
          },
        },
        required: ["steps"],
      },
    },
  ],
} as const;
const shared10 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    steps: [],
    tools: [
      {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    ],
  },
} as const;
const shared11 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Hi",
      },
    ],
    tools: [
      {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared12 = {
  id: "id-8",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-7",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared1,
      },
    },
  ],
} as const;
const shared13 = {
  id: "id-8",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-7",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared2,
      },
    },
  ],
} as const;
const shared14 = {
  type: "CUSTOM",
  name: "on_interrupt",
  value: shared2,
} as const;
const shared15 = {
  id: "id-6",
  role: "user",
  content: shared3,
} as const;
const shared16 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
    {
      id: "id-4",
      role: "assistant",
      content: "Hello! How can I assist you today?",
    },
  ],
} as const;
const shared17 = {
  id: "id-12",
  role: "user",
  content: shared4,
} as const;
const shared18 = {
  id: "id-12",
  role: "user",
  content: shared5,
} as const;
const shared19 = {
  type: "CUSTOM",
  name: "PredictState",
  value: [
    {
      state_key: "steps",
      tool: "plan_execution_steps",
      tool_argument: "steps",
    },
  ],
} as const;
const shared20 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-7",
  toolCallName: "plan_execution_steps",
  parentMessageId: "id-8",
} as const;
const shared21 = {
  id: "id-6",
  role: "user",
  content:
    "Plan a mission to Mars with the first step being Start The Planning",
} as const;
const shared22 = {
  id: "id-10",
  role: "assistant",
  content: "I understand. How can I help you with that?",
} as const;
const shared23 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-10",
  delta: "I understand. How ca",
} as const;
const shared24 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-10",
  delta: "n I help you with th",
} as const;
const shared25 = {
  id: "id-9",
  content: "Task steps generated.",
  role: "tool",
  toolCallId: "id-7",
} as const;
const shared26 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-4",
  delta: "Hello! How can I ass",
} as const;

export const humanInTheLoopPageEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatAndPerformSteps: [
    shared11,
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared26,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared10,
    shared16,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: {
          messages: [
            {
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
          ],
          steps: [],
          tools: [
            {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          ],
        },
        messages: [shared15],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared19,
    shared20,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'ion":"Crack eggs int',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'o bowl","status":"en',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'abled"},{"descriptio',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'n":"Preheat oven to ',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: '350F","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: ':"Mix and bake for 2',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: '5 min","status":"ena',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'bled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-7",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared8,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared15,
        shared12,
        shared25,
      ],
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "CUSTOM",
      name: "on_interrupt",
      value: shared1,
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: shared8,
        messages: [shared12, shared25],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Preheat oven to 350F, Mix and bake for 25 min",
            interruptEvent: shared1,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-10",
      role: "assistant",
    },
    shared23,
    shared24,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-10",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared15,
        shared12,
        shared25,
        shared22,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-11",
      input: {
        threadId: "id-1",
        runId: "id-11",
        state: shared6,
        messages: [shared18],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-13",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-13",
      delta: "No",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-13",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "tool_calls",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [
              {
                name: "plan_execution_steps",
                args: {
                  steps: [
                    {
                      description: "Crack eggs into bowl",
                      status: "enabled",
                    },
                    {
                      description: "Preheat oven to 350F",
                      status: "enabled",
                    },
                    {
                      description: "Mix and bake for 25 min",
                      status: "enabled",
                    },
                  ],
                },
                id: "id-7",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-9",
            tool_call_id: "id-7",
            artifact: null,
            status: "success",
          },
          {
            content: "I understand. How can I help you with that?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-10",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared5,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-12",
          },
          {
            content: "No",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared15,
        shared12,
        shared25,
        shared22,
        shared18,
        {
          id: "id-13",
          role: "assistant",
          content: "No",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
    },
  ],
  interactWithTheChatUsingPredefinedPromptsAndPerformSteps: [
    shared11,
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared26,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared10,
    shared16,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: {
          messages: [
            {
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
          ],
          steps: [],
          tools: [
            {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          ],
        },
        messages: [shared21],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared19,
    shared20,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-7",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared9,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared21,
        shared13,
        shared25,
      ],
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared14,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: shared9,
        messages: [shared13, shared25],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Design spacecraft, Launch mission",
            interruptEvent: shared2,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-10",
      role: "assistant",
    },
    shared23,
    shared24,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-10",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared21,
        shared13,
        shared25,
        shared22,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-11",
      input: {
        threadId: "id-1",
        runId: "id-11",
        state: shared7,
        messages: [shared17],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared19,
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-13",
      toolCallName: "plan_execution_steps",
      parentMessageId: "id-14",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-13",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-13",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "tool_calls",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [
              {
                name: "plan_execution_steps",
                args: {
                  steps: [
                    {
                      description: "Start The Planning",
                      status: "enabled",
                    },
                    {
                      description: "Design spacecraft",
                      status: "enabled",
                    },
                    {
                      description: "Launch mission",
                      status: "enabled",
                    },
                  ],
                },
                id: "id-7",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-9",
            tool_call_id: "id-7",
            artifact: null,
            status: "success",
          },
          {
            content: "I understand. How can I help you with that?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-10",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-12",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "tool_calls",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-14",
            tool_calls: [
              {
                name: "plan_execution_steps",
                args: {
                  steps: [
                    {
                      description: "Start The Planning",
                      status: "enabled",
                    },
                    {
                      description: "Design spacecraft",
                      status: "enabled",
                    },
                    {
                      description: "Launch mission",
                      status: "enabled",
                    },
                  ],
                },
                id: "id-13",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-15",
            tool_call_id: "id-13",
            artifact: null,
            status: "success",
          },
        ],
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared21,
        shared13,
        shared25,
        shared22,
        shared17,
        {
          id: "id-14",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-13",
              type: "function",
              function: {
                name: "plan_execution_steps",
                arguments: shared2,
              },
            },
          ],
        },
        {
          id: "id-15",
          content: "Task steps generated.",
          role: "tool",
          toolCallId: "id-13",
        },
      ],
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared14,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
    },
  ],
});
