import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Capture Strands AG-UI output as an event regression baseline
// Before accepting changes, verify whether the implementation regressed.
export const agenticChatReasoningPageEventTrace = defineEventTrace(
  import.meta.url,
  {
    shouldShowReasoningIndicatorAndThenTheResponse: [
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-2",
        input: {
          threadId: "id-1",
          runId: "id-2",
          state: {},
          messages: [
            {
              id: "id-3",
              role: "user",
              content: "What is the best car to buy?",
            },
          ],
          tools: [
            {
              name: "change_background",
              description:
                "Change the background color of the chat. Can be anything that the CSS background attribute accepts. Regular colors, linear of radial gradients etc.",
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description: "The background. Prefer gradients.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {},
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "What is the best car to buy?",
          },
        ],
      },
      {
        type: "REASONING_START",
        messageId: "id-4",
      },
      {
        type: "REASONING_MESSAGE_START",
        messageId: "id-4",
        role: "reasoning",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "The user wants a car",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: " recommendation. I s",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "hould consider relia",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "bility, value, fuel ",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "economy, and driving",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: " experience. Toyota ",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "Camry scores highest",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: " overall. Honda Civi",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "c is best for fuel e",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "conomy. Mazda3 for d",
      },
      {
        type: "REASONING_MESSAGE_CONTENT",
        messageId: "id-4",
        delta: "riving feel.",
      },
      {
        type: "REASONING_MESSAGE_END",
        messageId: "id-4",
      },
      {
        type: "REASONING_END",
        messageId: "id-4",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-5",
        role: "assistant",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "Based on my analysis",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: ", here are the top r",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ecommendations:\n\n1. ",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "**Toyota Camry** - B",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "est overall value wi",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "th excellent reliabi",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "lity\n2. **Honda Civi",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "c** - Great fuel eco",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "nomy and low mainten",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ance costs\n3. **Mazd",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "a3** - Best driving ",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "experience in its cl",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ass\n\nThe Toyota Camr",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "y stands out for its",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: " combination of reli",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ability, resale valu",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "e, and comfort.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-5",
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "What is the best car to buy?",
          },
          {
            id: "id-5",
            role: "assistant",
            content:
              "Based on my analysis, here are the top recommendations:\n\n1. **Toyota Camry** - Best overall value with excellent reliability\n2. **Honda Civic** - Great fuel economy and low maintenance costs\n3. **Mazda3** - Best driving experience in its class\n\nThe Toyota Camry stands out for its combination of reliability, resale value, and comfort.",
          },
        ],
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {},
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
        outcome: {
          type: "success",
        },
        usage: [
          {
            provider: "openai",
            model: "gpt-5.4",
            inputTokens: 0,
            outputTokens: 0,
            totalTokens: 0,
          },
        ],
      },
    ],
  },
);
