import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Preserve UTF-8 event payloads and distinct city tool calls after correcting capture metadata and Strands weather fixtures
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"steps":[{"description":"Crack eggs into bowl","status":"enabled"},{"description":"Preheat oven to 350F","status":"enabled"},{"description":"Mix and bake for 25 min","status":"enabled"}]}' as const;
const shared2 =
  '{"steps":[{"description":"Start The Planning","status":"enabled"},{"description":"Design spacecraft","status":"enabled"},{"description":"Launch mission","status":"enabled"}]}' as const;
const shared3 =
  '{"accepted":true,"steps":[{"description":"Preheat oven to 350F","status":"enabled"},{"description":"Mix and bake for 25 min","status":"enabled"}]}' as const;
const shared4 =
  '{"accepted":true,"steps":[{"description":"Design spacecraft","status":"enabled"},{"description":"Launch mission","status":"enabled"}]}' as const;
const shared5 =
  "Give me a plan to make brownies, there should be only one step with eggs and one step with oven, this is a strict requirement so adhere" as const;
const shared6 =
  "Does the planner include Start The Planning? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared7 =
  "Does the planner include eggs? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared8 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Hi",
      },
    ],
    tools: [
      {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared9 = {
  id: "id-8",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-7",
      type: "function",
      function: {
        name: "generate_task_steps",
        arguments: shared1,
      },
    },
  ],
} as const;
const shared10 = {
  id: "id-8",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-7",
      type: "function",
      function: {
        name: "generate_task_steps",
        arguments: shared2,
      },
    },
  ],
} as const;
const shared11 = {
  id: "id-10",
  content: shared3,
  role: "tool",
  toolCallId: "id-7",
} as const;
const shared12 = {
  id: "id-10",
  content: shared4,
  role: "tool",
  toolCallId: "id-7",
} as const;
const shared13 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-12",
  outcome: {
    type: "success",
  },
  usage: [
    {
      provider: "openai",
      model: "gpt-5.4",
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
  ],
} as const;
const shared14 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-2",
  outcome: {
    type: "success",
  },
  usage: [
    {
      provider: "openai",
      model: "gpt-5.4",
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
  ],
} as const;
const shared15 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-5",
  outcome: {
    type: "success",
  },
  usage: [
    {
      provider: "openai",
      model: "gpt-5.4",
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
  ],
} as const;
const shared16 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-9",
  outcome: {
    type: "success",
  },
  usage: [
    {
      provider: "openai",
      model: "gpt-5.4",
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
  ],
} as const;
const shared17 = {
  id: "id-6",
  role: "user",
  content: shared5,
} as const;
const shared18 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
    {
      id: "id-4",
      role: "assistant",
      content: "Hello! How can I assist you today?",
    },
  ],
} as const;
const shared19 = {
  id: "id-13",
  role: "user",
  content: shared6,
} as const;
const shared20 = {
  id: "id-13",
  role: "user",
  content: shared7,
} as const;
const shared21 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-7",
  toolCallName: "generate_task_steps",
  parentMessageId: "id-8",
} as const;
const shared22 = {
  id: "id-6",
  role: "user",
  content:
    "Plan a mission to Mars with the first step being Start The Planning",
} as const;
const shared23 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
  ],
} as const;
const shared24 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-11",
  delta: "Done! I've completed",
} as const;
const shared25 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-4",
  delta: "Hello! How can I ass",
} as const;
const shared26 = {
  id: "id-11",
  role: "assistant",
  content: "Done! I've completed that for you.",
} as const;

export const humanInTheLoopPageEventTrace = defineEventTrace(import.meta.url, {
  shouldInteractWithTheChatAndPerformSteps: [
    shared8,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared23,
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared25,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared18,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared14,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: {},
        messages: [shared17],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
      ],
    },
    shared21,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: shared1,
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-7",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
        shared9,
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared15,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-9",
      input: {
        threadId: "id-1",
        runId: "id-9",
        state: {},
        messages: [shared9, shared11],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
        shared9,
        shared11,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-11",
      role: "assistant",
    },
    shared24,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-11",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
        shared9,
        shared11,
        shared26,
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared16,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-12",
      input: {
        threadId: "id-1",
        runId: "id-12",
        state: {},
        messages: [shared20],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
        shared9,
        shared11,
        shared26,
        shared20,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-14",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "No",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-14",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared17,
        shared9,
        shared11,
        shared26,
        shared20,
        {
          id: "id-14",
          role: "assistant",
          content: "No",
        },
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared13,
  ],
  shouldInteractWithTheChatUsingPredefinedPromptsAndPerformSteps: [
    shared8,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared23,
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared25,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared18,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared14,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-5",
      input: {
        threadId: "id-1",
        runId: "id-5",
        state: {},
        messages: [shared22],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
      ],
    },
    shared21,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-7",
      delta: shared2,
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-7",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
        shared10,
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared15,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-9",
      input: {
        threadId: "id-1",
        runId: "id-9",
        state: {},
        messages: [shared10, shared12],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
        shared10,
        shared12,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-11",
      role: "assistant",
    },
    shared24,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-11",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
        shared10,
        shared12,
        shared26,
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared16,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-12",
      input: {
        threadId: "id-1",
        runId: "id-12",
        state: {},
        messages: [shared19],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
        shared10,
        shared12,
        shared26,
        shared19,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-14",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "No",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-14",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        shared22,
        shared10,
        shared12,
        shared26,
        shared19,
        {
          id: "id-14",
          role: "assistant",
          content: "No",
        },
      ],
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared13,
  ],
});
