import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Capture Strands AG-UI output as an event regression baseline
// Before accepting changes, verify whether the implementation regressed.
const shared1 = [
  {
    type: "RUN_STARTED",
    threadId: "id-1",
    runId: "id-2",
    input: {
      threadId: "id-1",
      runId: "id-2",
      state: {},
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Research the benefits of remote work",
        },
      ],
      tools: [],
      context: [],
      forwardedProps: {},
    },
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "STEP_STARTED",
    stepName: "agent:researcher",
  },
  {
    type: "TEXT_MESSAGE_START",
    messageId: "id-4",
    role: "assistant",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "Research: remote wor",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "k cuts commute time ",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "to zero.\nResearch: t",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "eams report longer s",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "tretches of focused ",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "work.\nResearch: onbo",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "arding takes deliber",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-4",
    delta: "ate effort.",
  },
  {
    type: "CUSTOM",
    name: "MultiAgentHandoff",
    value: {
      from_nodes: ["researcher"],
      to_nodes: ["analyst"],
    },
  },
  {
    type: "TEXT_MESSAGE_END",
    messageId: "id-4",
  },
  {
    type: "STEP_FINISHED",
    stepName: "agent:researcher",
  },
  {
    type: "STEP_STARTED",
    stepName: "agent:analyst",
  },
  {
    type: "TEXT_MESSAGE_START",
    messageId: "id-5",
    role: "assistant",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "Analysis: the time s",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "aved is real but une",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "venly distributed.\nA",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "nalysis: focus gains",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: " depend on meeting d",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "iscipline.\nAnalysis:",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: " onboarding is the c",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-5",
    delta: "ost centre to watch.",
  },
  {
    type: "CUSTOM",
    name: "MultiAgentHandoff",
    value: {
      from_nodes: ["analyst"],
      to_nodes: ["writer"],
    },
  },
  {
    type: "TEXT_MESSAGE_END",
    messageId: "id-5",
  },
  {
    type: "STEP_FINISHED",
    stepName: "agent:analyst",
  },
  {
    type: "STEP_STARTED",
    stepName: "agent:writer",
  },
  {
    type: "TEXT_MESSAGE_START",
    messageId: "id-6",
    role: "assistant",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "Summary: remote work",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: " reliably returns co",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "mmute time and prote",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "cts focus when meeti",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "ngs are kept in chec",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "k, but it moves the ",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "cost onto onboarding",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: ", which has to be de",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "signed rather than a",
  },
  {
    type: "TEXT_MESSAGE_CONTENT",
    messageId: "id-6",
    delta: "ssumed.",
  },
  {
    type: "TEXT_MESSAGE_END",
    messageId: "id-6",
  },
  {
    type: "STEP_FINISHED",
    stepName: "agent:writer",
  },
  {
    type: "STATE_SNAPSHOT",
    snapshot: {},
  },
  {
    type: "RUN_FINISHED",
    threadId: "id-1",
    runId: "id-2",
    outcome: {
      type: "success",
    },
    usage: [
      {
        provider: "openai",
        model: "gpt-5.4",
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
      },
    ],
  },
] as const;

export const multiAgentPageEventTrace = defineEventTrace(import.meta.url, {
  multiAgentGivesEachNodeItsOwnMessageInPipelineOrder: shared1,
  multiAgentIsolatesEachRunFromThePreviousOne: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Research the benefits of remote work",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:researcher",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Research: remote wor",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "k cuts commute time ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "to zero.\nResearch: t",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "eams report longer s",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "tretches of focused ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "work.\nResearch: onbo",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "arding takes deliber",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ate effort.",
    },
    {
      type: "CUSTOM",
      name: "MultiAgentHandoff",
      value: {
        from_nodes: ["researcher"],
        to_nodes: ["analyst"],
      },
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:researcher",
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:analyst",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-5",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "Analysis: the time s",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "aved is real but une",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "venly distributed.\nA",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "nalysis: focus gains",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: " depend on meeting d",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "iscipline.\nAnalysis:",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: " onboarding is the c",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "ost centre to watch.",
    },
    {
      type: "CUSTOM",
      name: "MultiAgentHandoff",
      value: {
        from_nodes: ["analyst"],
        to_nodes: ["writer"],
      },
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-5",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:analyst",
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:writer",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-6",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "Summary: remote work",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: " reliably returns co",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "mmute time and prote",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "cts focus when meeti",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "ngs are kept in chec",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "k, but it moves the ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "cost onto onboarding",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: ", which has to be de",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "signed rather than a",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "ssumed.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-6",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:writer",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      outcome: {
        type: "success",
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 0,
          outputTokens: 0,
          totalTokens: 0,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-7",
      input: {
        threadId: "id-1",
        runId: "id-7",
        state: {},
        messages: [
          {
            id: "id-8",
            role: "user",
            content: "Research the benefits of remote work",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:researcher",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-9",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "Research: remote wor",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "k cuts commute time ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "to zero.\nResearch: t",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "eams report longer s",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "tretches of focused ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "work.\nResearch: onbo",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "arding takes deliber",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "ate effort.",
    },
    {
      type: "CUSTOM",
      name: "MultiAgentHandoff",
      value: {
        from_nodes: ["researcher"],
        to_nodes: ["analyst"],
      },
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-9",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:researcher",
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:analyst",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-10",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "Analysis: the time s",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "aved is real but une",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "venly distributed.\nA",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "nalysis: focus gains",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: " depend on meeting d",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "iscipline.\nAnalysis:",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: " onboarding is the c",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: "ost centre to watch.",
    },
    {
      type: "CUSTOM",
      name: "MultiAgentHandoff",
      value: {
        from_nodes: ["analyst"],
        to_nodes: ["writer"],
      },
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-10",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:analyst",
    },
    {
      type: "STEP_STARTED",
      stepName: "agent:writer",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-11",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "Summary: remote work",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: " reliably returns co",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "mmute time and prote",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "cts focus when meeti",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "ngs are kept in chec",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "k, but it moves the ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "cost onto onboarding",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: ", which has to be de",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "signed rather than a",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "ssumed.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-11",
    },
    {
      type: "STEP_FINISHED",
      stepName: "agent:writer",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-7",
      outcome: {
        type: "success",
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 0,
          outputTokens: 0,
          totalTokens: 0,
        },
      ],
    },
  ],
  multiAgentRunsEveryGraphNodeAndReportsTheHandoffRoute: shared1,
});
