import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Preserve UTF-8 event payloads and distinct city tool calls after correcting capture metadata and Strands weather fixtures
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"recipe":{"title":"Pasta Aglio e Olio","skill_level":"Intermediate","special_preferences":[],"cooking_time":"45 min","ingredients":[{"icon":"🍝","name":"Pasta","amount":"400g"},{"icon":"🧂","name":"Salt","amount":"1 tsp"},{"icon":"🫒","name":"Olive Oil","amount":"4 tbsp"},{"icon":"🧄","name":"Garlic","amount":"6 cloves"},{"icon":"🍅","name":"Tomatoes","amount":"2 cups"}],"instructions":["Boil water and cook pasta until al dente","Slice garlic thinly and sauté in olive oil","Dice tomatoes and add to the pan","Season with salt to taste","Toss pasta with the sauce and serve"],"changes":""}}' as const;
const shared2 =
  'Please give me a pasta recipe of your choosing, but one of the ingredients should be "Pasta". Not a type of pasta, exactly the word "Pasta".' as const;
const shared3 = {
  id: "id-5",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-4",
      type: "function",
      function: {
        name: "generate_recipe",
        arguments: shared1,
      },
    },
  ],
} as const;
const shared4 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    recipe: {
      title: "Pasta Aglio e Olio",
      skill_level: "Intermediate",
      special_preferences: [],
      cooking_time: "45 min",
      ingredients: [
        {
          icon: "🍝",
          name: "Pasta",
          amount: "400g",
        },
        {
          icon: "🧂",
          name: "Salt",
          amount: "1 tsp",
        },
        {
          icon: "🫒",
          name: "Olive Oil",
          amount: "4 tbsp",
        },
        {
          icon: "🧄",
          name: "Garlic",
          amount: "6 cloves",
        },
        {
          icon: "🍅",
          name: "Tomatoes",
          amount: "2 cups",
        },
      ],
      instructions: [
        "Boil water and cook pasta until al dente",
        "Slice garlic thinly and sauté in olive oil",
        "Dice tomatoes and add to the pan",
        "Season with salt to taste",
        "Toss pasta with the sauce and serve",
      ],
      changes: "",
    },
  },
} as const;
const shared5 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    recipe: {
      title: "Make Your Recipe",
      skill_level: "Intermediate",
      cooking_time: "45 min",
      special_preferences: [],
      ingredients: [
        {
          icon: "🥕",
          name: "Carrots",
          amount: "3 large, grated",
        },
        {
          icon: "🌾",
          name: "All-Purpose Flour",
          amount: "2 cups",
        },
        {
          icon: "🍴",
          name: "Potatoes",
          amount: "12",
        },
      ],
      instructions: ["Preheat oven to 350°F (175°C)"],
    },
  },
} as const;
const shared6 = [
  {
    id: "id-3",
    role: "user",
    content: shared2,
  },
] as const;
const shared7 = {
  id: "id-6",
  content: '"Recipe updated successfully"',
  role: "tool",
  toolCallId: "id-4",
} as const;

export const sharedStatePageEventTrace = defineEventTrace(import.meta.url, {
  shouldInteractWithTheChatToGetARecipeOnPrompt: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {},
        messages: shared6,
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: shared6,
    },
    {
      type: "CUSTOM",
      name: "PredictState",
      value: [
        {
          state_key: "recipe",
          tool: "generate_recipe",
          tool_argument: "recipe",
        },
      ],
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-4",
      toolCallName: "generate_recipe",
      parentMessageId: "id-5",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"recipe":{"title":"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'Pasta Aglio e Olio",',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '"skill_level":"Inter',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'mediate","special_pr',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'eferences":[],"cooki',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ng_time":"45 min","i',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ngredients":[{"icon"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ':"🍝","name":"Pasta"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"amount":"400g"},{"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'icon":"🧂","name":"S',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'alt","amount":"1 tsp',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '"},{"icon":"🫒","nam',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'e":"Olive Oil","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nt":"4 tbsp"},{"icon',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '":"🧄","name":"Garli',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'c","amount":"6 clove',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 's"},{"icon":"🍅","na',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'me":"Tomatoes","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nt":"2 cups"}],"inst',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ructions":["Boil wat',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "er and cook pasta un",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'til al dente","Slice',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: " garlic thinly and s",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'auté in olive oil","',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "Dice tomatoes and ad",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'd to the pan","Seaso',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "n with salt to taste",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '","Toss pasta with t',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'he sauce and serve"]',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"changes":""}}',
    },
    shared4,
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: shared2,
        },
        shared3,
      ],
    },
    {
      type: "TOOL_CALL_RESULT",
      messageId: "id-6",
      toolCallId: "id-4",
      content: '"Recipe updated successfully"',
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: shared2,
        },
        shared3,
        shared7,
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-7",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: "Done! I've completed",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-7",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: shared2,
        },
        shared3,
        shared7,
        {
          id: "id-7",
          role: "assistant",
          content: "Done! I've completed that for you.",
        },
      ],
    },
    shared4,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      outcome: {
        type: "success",
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 327,
          outputTokens: 162,
          totalTokens: 489,
        },
      ],
    },
  ],
  shouldShareStateBetweenUIAndChat: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        state: {
          recipe: {
            title: "Make Your Recipe",
            skill_level: "Intermediate",
            cooking_time: "45 min",
            special_preferences: [],
            ingredients: [
              {
                icon: "🥕",
                name: "Carrots",
                amount: "3 large, grated",
              },
              {
                icon: "🌾",
                name: "All-Purpose Flour",
                amount: "2 cups",
              },
              {
                icon: "🍴",
                name: "Potatoes",
                amount: "12",
              },
            ],
            instructions: ["Preheat oven to 350°F (175°C)"],
          },
        },
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Please list all of the ingredients",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    shared5,
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Please list all of the ingredients",
        },
      ],
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Here are the ingredi",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ents:\n- Pasta: 400g\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "- Salt: 1 tsp\n- Oliv",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "e Oil: 4 tbsp\n- Garl",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ic: 6 cloves\n- Tomat",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "oes: 2 cups\n- Potato",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "es: 12\n- Carrots: 3\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "- All-Purpose Flour:",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: " 2 cups",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Please list all of the ingredients",
        },
        {
          id: "id-4",
          role: "assistant",
          content:
            "Here are the ingredients:\n- Pasta: 400g\n- Salt: 1 tsp\n- Olive Oil: 4 tbsp\n- Garlic: 6 cloves\n- Tomatoes: 2 cups\n- Potatoes: 12\n- Carrots: 3\n- All-Purpose Flour: 2 cups",
        },
      ],
    },
    shared5,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      outcome: {
        type: "success",
      },
      usage: [
        {
          provider: "openai",
          model: "gpt-5.4",
          inputTokens: 275,
          outputTokens: 42,
          totalTokens: 317,
        },
      ],
    },
  ],
});
