import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Declare Dojo SSE as UTF-8 and canonicalize contractual traces
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"steps":[{"description":"Crack eggs into bowl","status":"enabled"},{"description":"Preheat oven to 350F","status":"enabled"},{"description":"Mix and bake for 25 min","status":"enabled"}]}' as const;
const shared2 =
  '{"steps":[{"description":"Start The Planning","status":"enabled"},{"description":"Design spacecraft","status":"enabled"},{"description":"Launch mission","status":"enabled"}]}' as const;
const shared3 =
  "Give me a plan to make brownies, there should be only one step with eggs and one step with oven, this is a strict requirement so adhere" as const;
const shared4 =
  "Does the planner include Start The Planning? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared5 =
  "Does the planner include eggs? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared6 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {
        type: "human",
      },
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: shared3,
      additional_kwargs: {
        type: "human",
      },
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-7",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-9",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Crack eggs into bowl",
                status: "enabled",
              },
              {
                description: "Preheat oven to 350F",
                status: "enabled",
              },
              {
                description: "Mix and bake for 25 min",
                status: "enabled",
              },
            ],
          },
          id: "id-8",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-10",
      tool_call_id: "id-8",
      artifact: null,
      status: "success",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-12",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  steps: [
    {
      description: "Crack eggs into bowl",
      status: "enabled",
    },
    {
      description: "Preheat oven to 350F",
      status: "enabled",
    },
    {
      description: "Mix and bake for 25 min",
      status: "enabled",
    },
  ],
  tools: [
    {
      type: "function",
      name: "generate_task_steps",
      function: {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    },
  ],
} as const;
const shared7 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {
        type: "human",
      },
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content:
        "Plan a mission to Mars with the first step being Start The Planning",
      additional_kwargs: {
        type: "human",
      },
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-7",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-9",
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Start The Planning",
                status: "enabled",
              },
              {
                description: "Design spacecraft",
                status: "enabled",
              },
              {
                description: "Launch mission",
                status: "enabled",
              },
            ],
          },
          id: "id-8",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Task steps generated.",
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-10",
      tool_call_id: "id-8",
      artifact: null,
      status: "success",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-12",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  steps: [
    {
      description: "Start The Planning",
      status: "enabled",
    },
    {
      description: "Design spacecraft",
      status: "enabled",
    },
    {
      description: "Launch mission",
      status: "enabled",
    },
  ],
  tools: [
    {
      type: "function",
      name: "generate_task_steps",
      function: {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    },
  ],
} as const;
const shared8 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: shared3,
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-7",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-9",
        tool_calls: [
          {
            name: "plan_execution_steps",
            args: {
              steps: [
                {
                  description: "Crack eggs into bowl",
                  status: "enabled",
                },
                {
                  description: "Preheat oven to 350F",
                  status: "enabled",
                },
                {
                  description: "Mix and bake for 25 min",
                  status: "enabled",
                },
              ],
            },
            id: "id-8",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Task steps generated.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-10",
        tool_call_id: "id-8",
        artifact: null,
        status: "success",
      },
    ],
    steps: [
      {
        description: "Crack eggs into bowl",
        status: "enabled",
      },
      {
        description: "Preheat oven to 350F",
        status: "enabled",
      },
      {
        description: "Mix and bake for 25 min",
        status: "enabled",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
  },
} as const;
const shared9 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content:
          "Plan a mission to Mars with the first step being Start The Planning",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-7",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-9",
        tool_calls: [
          {
            name: "plan_execution_steps",
            args: {
              steps: [
                {
                  description: "Start The Planning",
                  status: "enabled",
                },
                {
                  description: "Design spacecraft",
                  status: "enabled",
                },
                {
                  description: "Launch mission",
                  status: "enabled",
                },
              ],
            },
            id: "id-8",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Task steps generated.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-10",
        tool_call_id: "id-8",
        artifact: null,
        status: "success",
      },
    ],
    steps: [
      {
        description: "Start The Planning",
        status: "enabled",
      },
      {
        description: "Design spacecraft",
        status: "enabled",
      },
      {
        description: "Launch mission",
        status: "enabled",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
  },
} as const;
const shared10 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    steps: [],
  },
} as const;
const shared11 = {
  messages: [
    {
      content: "Hi",
      additional_kwargs: {
        type: "human",
      },
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  steps: [],
  tools: [
    {
      type: "function",
      name: "generate_task_steps",
      function: {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    },
  ],
} as const;
const shared12 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    steps: [],
  },
} as const;
const shared13 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Hi",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
  },
} as const;
const shared14 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Hi",
      },
    ],
    tools: [
      {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared15 = {
  content: "",
  additional_kwargs: {
    invalid_tool_calls: [],
    usage_metadata: null,
  },
  response_metadata: {
    finish_reason: "tool_calls",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-9",
  tool_calls: [
    {
      name: "plan_execution_steps",
      args: {
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
      },
      id: "id-8",
      type: "tool_call",
    },
  ],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared16 = {
  content: "",
  additional_kwargs: {
    invalid_tool_calls: [],
    usage_metadata: null,
  },
  response_metadata: {
    finish_reason: "tool_calls",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-9",
  tool_calls: [
    {
      name: "plan_execution_steps",
      args: {
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
      },
      id: "id-8",
      type: "tool_call",
    },
  ],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared17 = {
  id: "id-9",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-8",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared1,
      },
    },
  ],
} as const;
const shared18 = {
  id: "id-9",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-8",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared2,
      },
    },
  ],
} as const;
const shared19 = {
  content: "I understand. How can I help you with that?",
  additional_kwargs: {
    invalid_tool_calls: [],
    usage_metadata: null,
  },
  response_metadata: {
    finish_reason: "stop",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-12",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared20 = {
  type: "CUSTOM",
  name: "on_interrupt",
  value: shared2,
} as const;
const shared21 = {
  content: shared4,
  additional_kwargs: {
    type: "human",
  },
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-15",
} as const;
const shared22 = {
  content: shared5,
  additional_kwargs: {
    type: "human",
  },
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-15",
} as const;
const shared23 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
    {
      id: "id-4",
      role: "assistant",
      content: "Hello! How can I assist you today?",
      toolCalls: [],
    },
  ],
} as const;
const shared24 = {
  id: "id-7",
  role: "user",
  content: shared3,
} as const;
const shared25 = {
  id: "id-15",
  role: "user",
  content: shared4,
} as const;
const shared26 = {
  id: "id-15",
  role: "user",
  content: shared5,
} as const;
const shared27 = {
  type: "CUSTOM",
  name: "PredictState",
  value: [
    {
      state_key: "steps",
      tool: "plan_execution_steps",
      tool_argument: "steps",
    },
  ],
} as const;
const shared28 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-8",
  toolCallName: "plan_execution_steps",
  parentMessageId: "id-9",
} as const;
const shared29 = {
  id: "id-7",
  role: "user",
  content:
    "Plan a mission to Mars with the first step being Start The Planning",
} as const;
const shared30 = {
  id: "id-12",
  role: "assistant",
  content: "I understand. How can I help you with that?",
  toolCalls: [],
} as const;
const shared31 = {
  id: "id-10",
  role: "tool",
  content: "Task steps generated.",
  toolCallId: "id-8",
} as const;
const shared32 = {
  id: "id-10",
  content: "Task steps generated.",
  role: "tool",
  toolCallId: "id-8",
} as const;
const shared33 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-12",
  delta: "I understand. How ca",
} as const;
const shared34 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-12",
  delta: "n I help you with th",
} as const;
const shared35 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-4",
  delta: "Hello! How can I ass",
} as const;

export const humanInTheLoopPageEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatAndPerformSteps: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    shared13,
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared12,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-4",
    },
    shared35,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared10,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared23,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: shared11,
        messages: [shared24],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared3,
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
        ],
        steps: [],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    shared28,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Crack eggs int',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'o bowl","status":"en',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'abled"},{"descriptio',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'n":"Preheat oven to ',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '350F","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ':"Mix and bake for 2',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '5 min","status":"ena',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'bled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared8,
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared24,
        shared17,
        shared31,
      ],
    },
    {
      type: "CUSTOM",
      name: "on_interrupt",
      value: shared1,
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          messages: [
            {
              content: "Hi",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: shared3,
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-7",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-9",
              tool_calls: [
                {
                  name: "plan_execution_steps",
                  args: {
                    steps: [
                      {
                        description: "Crack eggs into bowl",
                        status: "enabled",
                      },
                      {
                        description: "Preheat oven to 350F",
                        status: "enabled",
                      },
                      {
                        description: "Mix and bake for 25 min",
                        status: "enabled",
                      },
                    ],
                  },
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Task steps generated.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-10",
              tool_call_id: "id-8",
              artifact: null,
              status: "success",
            },
          ],
          steps: [
            {
              description: "Crack eggs into bowl",
              status: "enabled",
            },
            {
              description: "Preheat oven to 350F",
              status: "enabled",
            },
            {
              description: "Mix and bake for 25 min",
              status: "enabled",
            },
          ],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
        },
        messages: [shared17, shared32],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Preheat oven to 350F, Mix and bake for 25 min",
            interruptEvent: shared1,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    shared8,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-12",
    },
    shared33,
    shared34,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-12",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-12",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared24,
        shared17,
        shared31,
        shared30,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-13",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-14",
      input: {
        threadId: "id-1",
        runId: "id-14",
        state: shared6,
        messages: [shared26],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared3,
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          shared15,
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-10",
            tool_call_id: "id-8",
            artifact: null,
            status: "success",
          },
          shared19,
          shared22,
        ],
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-16",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: "No",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-16",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: shared3,
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          shared15,
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-10",
            tool_call_id: "id-8",
            artifact: null,
            status: "success",
          },
          shared19,
          shared22,
          {
            content: "No",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-16",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared24,
        shared17,
        shared31,
        shared30,
        shared26,
        {
          id: "id-16",
          role: "assistant",
          content: "No",
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-17",
    },
  ],
  interactWithTheChatUsingPredefinedPromptsAndPerformSteps: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    shared13,
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared12,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-4",
    },
    shared35,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared10,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared23,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: shared11,
        messages: [shared29],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
        ],
        steps: [],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    shared28,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared9,
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
      ],
    },
    shared20,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          messages: [
            {
              content: "Hi",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content:
                "Plan a mission to Mars with the first step being Start The Planning",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-7",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-9",
              tool_calls: [
                {
                  name: "plan_execution_steps",
                  args: {
                    steps: [
                      {
                        description: "Start The Planning",
                        status: "enabled",
                      },
                      {
                        description: "Design spacecraft",
                        status: "enabled",
                      },
                      {
                        description: "Launch mission",
                        status: "enabled",
                      },
                    ],
                  },
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Task steps generated.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-10",
              tool_call_id: "id-8",
              artifact: null,
              status: "success",
            },
          ],
          steps: [
            {
              description: "Start The Planning",
              status: "enabled",
            },
            {
              description: "Design spacecraft",
              status: "enabled",
            },
            {
              description: "Launch mission",
              status: "enabled",
            },
          ],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
        },
        messages: [shared18, shared32],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Design spacecraft, Launch mission",
            interruptEvent: shared2,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    shared9,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-12",
    },
    shared33,
    shared34,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-12",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-12",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
        shared30,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-13",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-14",
      input: {
        threadId: "id-1",
        runId: "id-14",
        state: shared7,
        messages: [shared25],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          shared16,
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-10",
            tool_call_id: "id-8",
            artifact: null,
            status: "success",
          },
          shared19,
          shared21,
        ],
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-16",
      toolCallName: "plan_execution_steps",
      parentMessageId: "id-17",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-16",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          shared16,
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-10",
            tool_call_id: "id-8",
            artifact: null,
            status: "success",
          },
          shared19,
          shared21,
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "tool_calls",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-17",
            tool_calls: [
              {
                name: "plan_execution_steps",
                args: {
                  steps: [
                    {
                      description: "Start The Planning",
                      status: "enabled",
                    },
                    {
                      description: "Design spacecraft",
                      status: "enabled",
                    },
                    {
                      description: "Launch mission",
                      status: "enabled",
                    },
                  ],
                },
                id: "id-16",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Task steps generated.",
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-18",
            tool_call_id: "id-16",
            artifact: null,
            status: "success",
          },
        ],
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
        shared30,
        shared25,
        {
          id: "id-17",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-16",
              type: "function",
              function: {
                name: "plan_execution_steps",
                arguments: shared2,
              },
            },
          ],
        },
        {
          id: "id-18",
          role: "tool",
          content: "Task steps generated.",
          toolCallId: "id-16",
        },
      ],
    },
    shared20,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-19",
    },
  ],
});
