name: unit

on:
  push:
    branches: [main]
    paths:
      - "sdks/community/dart/**"
      - ".github/workflows/unit-dart-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/community/dart/**"
      - ".github/workflows/unit-dart-sdk.yml"

permissions:
  contents: read

jobs:
  dart:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdks/community/dart

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          lfs: true
          persist-credentials: false

      - name: Set up Dart
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d  # v1.8.1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test --exclude-tags requires-server
