package com.agui.community.core.message;

/**
 * The role of a {@link Message}, identifying which participant in the
 * conversation produced it.
 *
 * @see <a href="https://docs.ag-ui.com/concepts/messages">AG-UI Messages</a>
 */
public enum Role {

    /** A message from the developer, typically used for instructions. */
    DEVELOPER("developer"),

    /** A system message, typically used to set context or behaviour. */
    SYSTEM("system"),

    /** A message generated by the assistant (the agent). */
    ASSISTANT("assistant"),

    /** A message from the end user. */
    USER("user"),

    /** The result of a tool call, fed back into the conversation. */
    TOOL("tool"),

    /** A reasoning (chain-of-thought) message produced by the assistant. */
    REASONING("reasoning");

    private final String value;

    Role(String value) {
        this.value = value;
    }

    /**
     * @return the wire value of this role as used in the AG-UI protocol
     */
    public String value() {
        return value;
    }

    /**
     * Resolves a {@link Role} from its wire value.
     *
     * @param value the protocol value (e.g. {@code "assistant"})
     * @return the matching role
     * @throws IllegalArgumentException if no role matches the given value
     */
    public static Role fromValue(String value) {
        for (Role role : values()) {
            if (role.value.equals(value)) {
                return role;
            }
        }
        throw new IllegalArgumentException("Unknown role: " + value);
    }
}
