/**
 * Generation-time guards for the protobuf translation emitter.
 *
 * The drift gate in generator.test.ts compares the generator against its own
 * committed output, so it is silent about anything the emitter never wrote in
 * the first place: a schema change that SHOULD have reached the mapper and did
 * not regenerates byte for byte and passes. These tests close that gap by
 * generating from a mutated schema and reading the emitted source.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { buildModel } from "../generator/ir";
import { buildWireModel } from "../generator/protobuf";
import { emitProtoTranslation } from "../generator/proto-translation";
import { FREEZE_PATH, SCHEMA_PATH } from "../generator/generate";

const RAW = readFileSync(SCHEMA_PATH, "utf8");
const FREEZE = readFileSync(FREEZE_PATH, "utf8");

/** A deep copy, so each case mutates the schema without touching the others. */
const freshSchema = (): Record<string, any> => JSON.parse(RAW);

const emitFrom = (schema: unknown): string =>
  emitProtoTranslation(buildWireModel(buildModel(schema as never), FREEZE));

describe("the protobuf translation emitter", () => {
  /**
   * BaseEvent's fields are listed once, in the schema. The emitter used to
   * repeat them as a literal destructuring pattern and a literal object, so a
   * field added to BaseEvent reached events.proto — where the wire model reads
   * the schema — and never reached the mapper. Every generated file still
   * regenerated byte for byte, and the field simply stopped crossing the wire.
   */
  it("writes every BaseEvent field into encode, whatever the schema adds", () => {
    const schema = freshSchema();
    schema.$defs.BaseEvent.properties.traceId = {
      type: "string",
      description: "A field added to BaseEvent after this build shipped.",
    };

    const source = emitFrom(schema);

    // Destructured off the validated event...
    expect(source).toMatch(
      /const \{[^}]*\btraceId\b[^}]*\.\.\.rest \} =\s*validatedEvent/,
    );
    // ...and put back on the wire's base_event, rather than riding `rest` into
    // a per-event message that has no field for it.
    expect(source).toMatch(/baseEvent: \{[\s\S]*?\btraceId\b[\s\S]*?\n {6}\},/);
  });

  it("still writes the BaseEvent fields the schema has today", () => {
    const source = emitFrom(freshSchema());

    for (const name of ["type", "timestamp", "rawEvent", "metadata"]) {
      expect(source).toMatch(
        new RegExp(`const \\{[^}]*\\b${name}\\b[^}]*\\.\\.\\.rest \\} =`),
      );
    }
    expect(source).toMatch(
      /baseEvent: \{[\s\S]*?\btimestamp\b[\s\S]*?\brawEvent\b[\s\S]*?\n {6}\},/,
    );
  });

  /**
   * One identity, derived twice: encode picks its envelope key by camelCasing
   * the EventType VALUE, while decode's ENVELOPE_TYPE table is keyed by the
   * entry protobuf.ts names after the definition NAME. They agree for all 31
   * events today by convention alone — nothing made them. If they ever
   * disagreed, encode would write an arm decode does not read, and the round
   * trip would fail only at runtime.
   */
  it("refuses a schema where encode's key and the envelope's key disagree", () => {
    const schema = freshSchema();
    // The definition stays RunStartedEvent — so the envelope entry stays
    // "run_started" — while its EventType value is renamed.
    schema.$defs.EventType.enum = schema.$defs.EventType.enum.map(
      (value: string) => (value === "RUN_STARTED" ? "RUN_BEGAN" : value),
    );
    schema.$defs.RunStartedEvent.properties.type.const = "RUN_BEGAN";

    // Named on the offence, not on either spelling alone: /runStarted/ is the
    // arm the untouched schema writes everywhere, so the alternation passed on
    // messages that had nothing to do with the two having parted.
    expect(() => emitFrom(schema)).toThrow(
      /encode writes the envelope arm "runBegan"/,
    );
  });

  it("accepts the schema as it stands", () => {
    expect(() => emitFrom(freshSchema())).not.toThrow();
  });
});
